import { useEffect, useRef, useState } from 'react';
import FilterPanel from '../../components/FilterPanel.jsx';
import WorkspacePicker from '../../components/WorkspacePicker.jsx';
import Icon from '../../components/Icon.jsx';
import { EmptyState, InlineMessage, LoadingState } from '../../components/Feedback.jsx';
import { statuses, deadline } from '../../lib/content.js';
import { messageFor } from '../../lib/messages.js';
import TaskPanel from './TaskPanel.jsx';
import MyTaskScope from './MyTaskScope.jsx';
import { defaultFilters, myTaskParams, readMyTaskFilters } from './my-task-filters.js';
import './my-tasks.css';
const groups = { overdue: ['Quá hạn','calendar'], today: ['Hạn chót hôm nay','calendar'], upcoming: ['Sắp tới','calendar'], no_deadline: ['Chưa có hạn chót','tasks'], completed: ['Đã hoàn thành','check'] };
const priorities = { high:'Ưu tiên cao',medium:'Ưu tiên vừa',low:'Ưu tiên thấp' };
export default function MyTasks({ api }) {
  const [filters,setFilters]=useState(()=>readMyTaskFilters()),[data,setData]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0),[reset,setReset]=useState(0),[selected,setSelected]=useState(null);
  const generation=useRef(0),pending=useRef(false),scope=useRef('');
  const query=myTaskParams(filters).toString(),invalid=Boolean(filters.from&&filters.to&&filters.from>filters.to);
  const returnTo='#mine?'+query;
  function change(fields) { const next={...filters,...fields};if(myTaskParams(next).toString()===query)return;generation.current++;setData(null);setError('');setBusy(true);setFilters(next); }
  useEffect(()=>{const handle=()=>{if(location.hash.split('?')[0]==='#mine')setFilters(readMyTaskFilters());};window.addEventListener('hashchange',handle);return()=>window.removeEventListener('hashchange',handle);},[]);
  useEffect(()=>{history.replaceState(history.state,'',returnTo);},[query]);
  async function load(token,cursor) {
    setBusy(true);setError('');
    try { const result=await api.request('/my-tasks?'+query+'&limit=12'+(cursor?'&cursor='+encodeURIComponent(cursor):''));if(token!==generation.current)return;setData(old=>({...result,items:cursor&&old?[...old.items,...result.items].filter((item,index,all)=>all.findIndex(value=>value.id===item.id)===index):result.items})); }
    catch(error) {if(token===generation.current){if(!cursor||[401,403,404].includes(error.status))setData(null);setError(messageFor(error));}}
    finally {if(token===generation.current){setBusy(false);pending.current=false;}}
  }
  useEffect(()=>{const token=++generation.current;pending.current=false;if(scope.current!==query)setData(null);scope.current=query;setError('');if(invalid){setData(null);setBusy(false);return;}setBusy(true);const timer=setTimeout(()=>load(token),300);return()=>{clearTimeout(timer);generation.current++;};},[query,revision]);
  function more() {if(busy||pending.current||!data?.nextCursor)return;pending.current=true;load(generation.current,data.nextCursor);}
  function resetFilters() {change({...defaultFilters});setReset(value=>value+1);}
  const counts=data?.groupCounts;
  return <main className="studio-my-tasks"><header className="my-task-heading"><div><p className="eyebrow">KHÔNG GIAN CÁ NHÂN</p><h1>Công việc của tôi</h1><p>Theo dõi công việc được giao cho bạn qua các Workspace và Project.</p></div><button disabled={busy} onClick={()=>setRevision(value=>value+1)}><Icon name="refresh"/>Làm mới công việc</button></header>
    <section className="my-task-summary" aria-label="Tổng quan công việc phù hợp bộ lọc"><Summary label="Cần xử lý" value={counts?counts.overdue+counts.today:null} detail={counts?`${counts.overdue} quá hạn · ${counts.today} đến hạn hôm nay`:'Đang lấy số liệu'} tone="urgent"/><Summary label="Sắp tới" value={counts?.upcoming} detail="Các hạn chót từ ngày mai trở đi" tone="upcoming"/><Summary label="Đã hoàn thành" value={counts?.completed} detail="Trong phạm vi bộ lọc hiện tại" tone="completed"/></section>
    <section className="my-task-controls"><div className="my-task-quick" aria-label="Lọc nhanh công việc">{[['open','Chưa hoàn thành'],['all','Tất cả'],['done','Đã hoàn thành']].map(([value,label])=><button key={value} aria-pressed={filters.status===value&&!filters.overdue} onClick={()=>change({status:value,overdue:false})}>{label}</button>)}<button aria-pressed={filters.overdue} onClick={()=>change({status:'open',overdue:!filters.overdue})}><Icon name="calendar"/>Quá hạn</button></div>
    <FilterPanel compact advancedLabel="Lọc nâng cao"><label>Tìm Task<input type="search" maxLength={200} placeholder="Tìm theo tên hoặc mã Task…" value={filters.q} onChange={event=>change({q:event.target.value})}/></label><label>Trạng thái Task<select aria-label="Trạng thái Task" value={filters.status} onChange={event=>change({status:event.target.value,overdue:false})}><option value="open">Chưa hoàn thành</option><option value="all">Tất cả</option>{Object.entries(statuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><WorkspacePicker api={api} value={filters.workspaceId} resetKey={reset} filterActive={Boolean(filters.workspaceId)} onChange={value=>change({workspaceId:value,projectId:'',labelId:''})}/><MyTaskScope api={api} workspaceId={filters.workspaceId} projectId={filters.projectId} labelId={filters.labelId} filterActive={Boolean(filters.projectId||filters.labelId)} onProject={value=>change({projectId:value,labelId:''})} onLabel={value=>change({labelId:value})}/><label>Ưu tiên<select aria-label="Ưu tiên" value={filters.priority} onChange={event=>change({priority:event.target.value})}><option value="">Tất cả mức ưu tiên</option>{Object.entries(priorities).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Phạm vi lưu trữ<select aria-label="Phạm vi lưu trữ" value={filters.state} onChange={event=>change({state:event.target.value})}><option value="active">Đang hoạt động</option><option value="archived">Đã lưu trữ</option><option value="all">Tất cả</option></select></label><label>Thời gian<select aria-label="Thời gian" value={filters.timeField} onChange={event=>change({timeField:event.target.value})}><option value="createdAt">Ngày tạo</option><option value="dueAt">Deadline</option></select></label><label>Từ ngày<input type="date" value={filters.from} onChange={event=>change({from:event.target.value})}/></label><label>Đến ngày<input type="date" value={filters.to} onChange={event=>change({to:event.target.value})}/></label><button onClick={resetFilters}>Xóa bộ lọc Task</button></FilterPanel></section>
    <p className="my-task-result" aria-live="polite">{data?`${data.total} công việc phù hợp · ${data.workspaceCount} Workspace`:'Chỉ công việc được giao cho bạn'} · Mới tạo trước trong từng nhóm · Giờ Việt Nam</p>
    {invalid&&<InlineMessage>Ngày bắt đầu phải trước hoặc bằng ngày kết thúc.</InlineMessage>}{error&&<InlineMessage>{error}<button disabled={busy} onClick={()=>setRevision(value=>value+1)}>Thử lại công việc</button></InlineMessage>}{busy&&<LoadingState>Đang tải công việc…</LoadingState>}
    {data&&<div className="my-task-groups" aria-busy={busy}>{!data.total?<EmptyState>Không có công việc phù hợp bộ lọc. Thử đổi từ khóa hoặc xóa bộ lọc.</EmptyState>:Object.entries(groups).filter(([key])=>data.groupCounts[key]>0).map(([key,[label,icon]])=>{const items=data.items.filter(task=>task.deadlineGroup===key);return <section className={'my-task-group group-'+key} key={key} aria-label={label}><div className="my-task-group-heading"><h2><Icon name={icon}/>{label}<span>{data.groupCounts[key]}</span></h2><p>{items.length}/{data.groupCounts[key]} đã tải</p></div>{items.map(task=><TaskRow key={task.id} task={task} returnTo={returnTo} onOpen={()=>setSelected({id:task.id,projectId:task.projectId})}/>)}{!items.length&&<p className="group-not-loaded">Nhóm này chưa có trong trang đã tải. Chọn “Tải thêm công việc” để tiếp tục.</p>}</section>;})}{data.nextCursor&&<button className="my-task-load-more" disabled={busy} onClick={more}>Tải thêm công việc</button>}</div>}
    {data?.asOf&&<p className="my-task-asof">Số liệu tại {new Date(data.asOf).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}. Làm mới để cập nhật hạn và quyền truy cập.</p>}
    {selected&&<TaskPanel api={api} id={selected.id} projectId={selected.projectId} returnTo={returnTo} onClose={()=>{setSelected(null);setRevision(value=>value+1);}}/>}
  </main>;
}
function Summary({label,value,detail,tone}) {return <div className={'my-task-stat '+tone}><p>{label}</p><strong>{value??'—'}</strong><p><Icon name={tone==='completed'?'check':'calendar'}/>{detail}</p></div>;}
function TaskRow({task,returnTo,onOpen}) {
  const href=`#task/${task.id}?returnTo=${encodeURIComponent(returnTo)}`;
  return <article className={'my-task-row'+(task.overdue?' is-overdue':'')}><div className="my-task-row-body"><div className="my-task-row-context">{task.code&&<span className="task-code">{task.code}</span>}<a href={'#workspace/'+task.workspaceId}>{task.workspaceName}</a><Icon name="chevron-right"/><a href={'#project/'+task.projectId}>{task.projectName}</a></div><h3><a href={href} onClick={event=>{if(!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&!event.altKey){event.preventDefault();onOpen();}}}>{task.title}</a></h3><div className="my-task-row-tags"><span className={'task-priority priority-'+task.priority}>{priorities[task.priority]}</span><span className={task.overdue?'overdue-chip':'my-task-date'}><Icon name="calendar"/>{task.status==='done' ? task.completedAt?'Hoàn thành '+new Date(task.completedAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'Chưa ghi nhận ngày hoàn thành' : deadline(task.dueAt)}</span>{task.readOnly&&<span><Icon name="archive"/>Chỉ đọc · Đã lưu trữ</span>}{task.labels?.map(label=><span key={label.id} className={'label-color-'+label.color}>{label.name}{label.archivedAt?' · Đã lưu trữ':''}</span>)}{task.checklist?.length>0&&<span><Icon name="check"/>{task.checklist.filter(item=>item.checked).length}/{task.checklist.length} mục</span>}</div></div><div className="my-task-row-end"><span className={'pill status-'+task.status}>{statuses[task.status]}</span><a href={href} className="my-task-open" aria-label={'Mở toàn trang '+task.title}><Icon name="chevron-right"/></a></div></article>;
}
