import { useEffect, useRef, useState } from 'react';
import { InlineMessage } from '../../components/Feedback.jsx';
import { confirmDialog, notify } from '../../components/NotificationProvider.jsx';
import { useDraftGuard } from '../../lib/draft-navigation.js';
import { isUncertainMutation } from '../../lib/mutation-outcome.js';
import { messageFor } from '../../lib/messages.js';
export default function TaskChecklist({ api, task, disabled, onTask, onComposing }) {
  const [editing, setEditing] = useState(false), [items, setItems] = useState([]), [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false), [uncertain, setUncertain] = useState(false), [error, setError] = useState(''), pending = useRef(false);
  useDraftGuard({ dirty, busy, message: 'Bỏ checklist chưa lưu?' });
  useEffect(() => { onComposing?.(editing || busy || uncertain); return () => onComposing?.(false); }, [editing, busy, uncertain, onComposing]);
  async function write(body, itemId) { if (pending.current || uncertain) return; pending.current = true; setBusy(true); setError(''); try { const result = await api.request(`/tasks/${task.id}/checklist${itemId ? '/' + itemId : ''}`, { method: 'PATCH', body: { expectedVersion: task.version, ...body } }); onTask(result.task); setEditing(false); setDirty(false); notify('Đã cập nhật checklist.'); } catch (error) { setUncertain(isUncertainMutation(error)); setError(isUncertainMutation(error) ? 'Chưa xác nhận kết quả. Đóng checklist và tải lại Task trước khi gửi tiếp.' : messageFor(error)); } finally { pending.current = false; setBusy(false); } }
  async function cancel() { if (!busy && (!dirty || await confirmDialog(uncertain ? 'Đóng checklist và tải lại để kiểm tra kết quả?' : 'Bỏ checklist chưa lưu?'))) { setEditing(false); setDirty(false); setUncertain(false); setError(''); onComposing?.(false); if (uncertain) onTask(null); } }
  const total = task.checklist?.length ?? 0, checked = task.checklist?.filter(item => item.checked).length ?? 0;
  return <section className="task-checklist"><div className="section-heading"><h2>Checklist <span>{checked}/{total}</span></h2>{task.permissions.checklistStructure && !editing && <button disabled={busy || disabled || uncertain} onClick={() => { setItems((task.checklist ?? []).map(item => ({ id: item.id, text: item.text }))); setEditing(true); }}>Sửa checklist</button>}</div>{editing ? <form onSubmit={event => { event.preventDefault(); if (items.some(item => !item.text.trim() || item.text.length > 300 || /[\u0000-\u001f\u007f\u2028\u2029]/u.test(item.text))) { setError('Mỗi mục cần nội dung một dòng, tối đa 300 ký tự.'); return; } write({ items: items.map(item => ({ ...(item.id ? { id: item.id } : {}), text: item.text.trim() })) }); }}><fieldset disabled={busy || uncertain}>{items.map((item, index) => <div className="checklist-edit-row" key={item.id ?? item.key}><input aria-label={`Mục checklist ${index+1}`} maxLength={300} required value={item.text} onChange={event => { setItems(old => old.map((value,i) => i === index ? { ...value, text: event.target.value } : value)); setDirty(true); }} /><button type="button" aria-label={`Bỏ mục checklist ${index+1}`} onClick={() => { setItems(old => old.filter((_,i) => i !== index)); setDirty(true); }}>Bỏ</button></div>)}<button type="button" disabled={items.length >= 100} onClick={() => { setItems(old => [...old, { key: crypto.randomUUID(), text: '' }]); setDirty(true); }}>Thêm mục checklist</button></fieldset><div className="buttons"><button type="button" disabled={busy} onClick={cancel}>Hủy checklist</button><button className="primary" disabled={busy || uncertain}>Lưu checklist</button></div></form> : <>{!total && <p>Chưa có mục checklist.</p>}{task.checklist?.map(item => <label className="checklist-item" key={item.id}><input type="checkbox" checked={item.checked} disabled={busy || disabled || uncertain || !task.permissions.checklistTick} onChange={event => write({ checked: event.target.checked }, item.id)} /><span>{item.text}</span></label>)}</>}{error && <InlineMessage>{error}</InlineMessage>}{uncertain && !editing && <button onClick={cancel}>Đóng trạng thái và tải lại Task</button>}</section>;
}
