import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import FormField from '../../components/FormField.jsx';
import useDialogFocus from '../../components/useDialogFocus.js';
import { InlineMessage, LoadingState, EmptyState } from '../../components/Feedback.jsx';
import { confirmDialog, notify } from '../../components/NotificationProvider.jsx';
import { useDraftGuard } from '../../lib/draft-navigation.js';
import { messageFor } from '../../lib/messages.js';
import { isUncertainMutation } from '../../lib/mutation-outcome.js';
import { statuses } from '../../lib/content.js';
const stateLabels = { pending: 'Chờ duyệt', approved: 'Đã duyệt', rejected: 'Đã từ chối', cancelled: 'Đã hủy' };
const cancellations = { parent_archived: 'Project hoặc Workspace được lưu trữ', parent_unavailable: 'Không còn tài nguyên cha', task_unavailable: 'Task không còn khả dụng', task_already_open: 'Task đã được mở lại', requester_ineligible: 'Người gửi không còn đủ điều kiện', requester_access_lost: 'Người gửi mất quyền truy cập' };
export default function TaskReopen({ api, task, disabled, onTask }) {
  const [open, setOpen] = useState(Boolean(task.pendingReopenRequestId)), [data, setData] = useState({ items: [] }), [busy, setBusy] = useState(false), [error, setError] = useState(''), [revision, setRevision] = useState(0), [action, setAction] = useState(null), generation = useRef(0);
  async function load(cursor, token = generation.current) { setBusy(true); setError(''); try { const result = await api.request(`/tasks/${task.id}/reopen-requests?limit=12${cursor ? '&cursor='+encodeURIComponent(cursor) : ''}`); if (token === generation.current) setData(old => ({ ...result, items: cursor ? [...old.items, ...result.items] : result.items })); } catch (error) { if (token === generation.current) { setError(messageFor(error)); setData({ items: [] }); } } finally { if (token === generation.current) setBusy(false); } }
  useEffect(() => { if (task.pendingReopenRequestId) setOpen(true); }, [task.pendingReopenRequestId]);
  useEffect(() => { if (!open) return; const token = ++generation.current; setData({ items: [] }); load(null, token); return () => { generation.current++; }; }, [task.id, task.version, task.pendingReopenRequestId, open, revision]);
  return <section className="task-reopen"><div className="section-heading"><h2>Mở lại Task</h2><button onClick={() => setOpen(value=>!value)}>{open ? 'Thu gọn yêu cầu' : 'Xem yêu cầu mở lại'}</button></div><p>Task Done cần lý do để mở lại. Sau khi bị từ chối, người gửi chờ 24 giờ; tối đa 3 yêu cầu cho mỗi Task/người trong 7 ngày. Không giới hạn tổng số lần mở lại suốt vòng đời Task.</p>{task.permissions.requestReopen && <button className="primary" disabled={disabled || busy} onClick={() => setAction({ kind:'request' })}>Yêu cầu mở lại</button>}{task.pendingReopenRequestId && <InlineMessage tone="info">Có yêu cầu đang chờ xử lý. Người gửi không thể tự duyệt; trạng thái Task vẫn là Done cho đến khi được mở lại.</InlineMessage>}{open && <><button disabled={busy} onClick={()=>setRevision(value=>value+1)}>Tải lại yêu cầu</button>{error && <InlineMessage>{error}</InlineMessage>}{busy && <LoadingState>Đang tải yêu cầu…</LoadingState>}<ol className="reopen-list">{data.items.map(item=><li key={item.id}><strong>{stateLabels[item.state]}</strong><p>{item.requester?.displayName ?? 'Người dùng không còn khả dụng'} · Muốn chuyển sang {statuses[item.targetStatus]}</p><p>{item.reason}</p><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</time>{item.resolutionReason && <p>Kết quả: {item.state==='cancelled' ? cancellations[item.resolutionReason] ?? 'Yêu cầu không còn hợp lệ theo quyền/trạng thái hiện tại' : item.resolutionReason}</p>}{item.resolvedBy && <p>Người xử lý: {item.resolvedBy.displayName}</p>}{item.permissions.review && task.permissions.manageReopen && <div className="buttons"><button disabled={disabled || busy} onClick={()=>setAction({kind:'approve',item})}>Duyệt mở lại</button><button disabled={disabled || busy} onClick={()=>setAction({kind:'reject',item})}>Từ chối yêu cầu</button></div>}</li>)}</ol>{!busy && !error && !data.items.length && <EmptyState>Chưa có yêu cầu mở lại.</EmptyState>}{data.nextCursor && <button disabled={busy} onClick={()=>load(data.nextCursor)}>Tải thêm yêu cầu</button>}</>}{action && <ReopenDialog api={api} task={task} action={action} onClose={()=>setAction(null)} onSaved={result=>{setAction(null);setOpen(true);setRevision(value=>value+1);onTask(result.task ?? null);}} />}</section>;
}
function ReopenDialog({ api, task, action, onClose, onSaved }) {
  const [reason,setReason]=useState(''),[targetStatus,setTarget]=useState('todo'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[uncertain,setUncertain]=useState(false),panel=useRef(null),pending=useRef(false),close=useRef(null);
  useDraftGuard({dirty:Boolean(reason||targetStatus!=='todo'),busy,message:'Bỏ nội dung mở lại Task chưa gửi?'});
  close.current=async()=>{if(!pending.current&&((!reason&&targetStatus==='todo')||await confirmDialog(uncertain?'Đóng và tải lại Task để kiểm tra kết quả?':'Bỏ nội dung mở lại Task chưa gửi?'))) {onClose(); if(uncertain) onSaved({});}};
  useDialogFocus(panel,()=>close.current());
  const title=action.kind==='request'?'Yêu cầu mở lại':action.kind==='approve'?'Duyệt mở lại':'Từ chối yêu cầu';
  async function submit(event) { event.preventDefault(); if(pending.current||uncertain||!reason.trim()||/[\u0000-\u001f\u007f\u2028\u2029]/u.test(reason)) return;pending.current=true;setBusy(true);setError('');try{const result=await api.request(`/tasks/${task.id}/reopen-requests${action.item?'/'+action.item.id+'/review':''}`,{method:'POST',body:action.kind==='request'?{expectedVersion:task.version,reason:reason.trim(),targetStatus}:{expectedVersion:action.item.version,expectedTaskVersion:task.version,decision:action.kind,reason:reason.trim()}});notify(result.code==='REOPEN_REQUEST_CANCELLED'?'Yêu cầu không còn hợp lệ; Task không được mở lại.':action.kind==='request'?'Đã gửi yêu cầu; Task vẫn Done.':action.kind==='approve'?'Đã duyệt và mở lại Task.':'Đã từ chối yêu cầu.');onSaved(result);}catch(error){setUncertain(isUncertainMutation(error));setError(isUncertainMutation(error)?'Chưa xác nhận kết quả. Đóng và tải lại trước khi gửi tiếp.':messageFor(error));}finally{pending.current=false;setBusy(false);}}
  return createPortal(<div className="overlay"><section ref={panel} tabIndex={-1} className="dialog reopen-dialog" role="dialog" aria-modal="true" aria-labelledby="reopen-dialog-title"><h2 id="reopen-dialog-title">{title}</h2><p>{task.code ?? 'Task'} · {task.title}</p>{action.item && <p>Yêu cầu của {action.item.requester?.displayName}: {action.item.reason}. Trạng thái đích: {statuses[action.item.targetStatus]}.</p>}<form onSubmit={submit}><fieldset disabled={busy||uncertain}>{action.kind==='request'&&<FormField label="Trạng thái muốn mở lại">{props=><select {...props} value={targetStatus} onChange={event=>setTarget(event.target.value)}><option value="todo">Chưa làm</option><option value="in_progress">Đang làm</option></select>}</FormField>}<FormField label="Lý do" hint="Một dòng, tối đa 2.000 ký tự. Bắt buộc cả khi duyệt/từ chối.">{props=><input {...props} required maxLength={2000} value={reason} onChange={event=>setReason(event.target.value)}/>}</FormField></fieldset>{error&&<InlineMessage>{error}</InlineMessage>}<div className="buttons"><button type="button" disabled={busy} onClick={()=>close.current()}>Đóng</button><button className="primary" disabled={busy||uncertain||!reason.trim()}>{busy?'Đang xử lý…':title}</button></div></form></section></div>,document.body);
}

