import { translateAuthText } from '../features/auth/auth-translations.js';
const english = {
  "Tạo {date}": "Created {date}",
  "Bộ lọc danh sách": "List filters", "Sắp xếp:": "Sort:", "Mới tạo trước": "Newest first", "Tìm kiếm & bộ lọc": "Search & filters", "Thu hẹp danh sách theo nhu cầu của bạn": "Narrow the list to what you need",
  "KHÔNG GIAN LÀM VIỆC CỦA BẠN": "YOUR WORKSPACE",
  "Chọn một Workspace để bắt đầu. Cùng đội ngũ biến ý tưởng thành công việc.": "Choose a workspace and start turning ideas into work with your team.",
  "Tạo Workspace": "Create workspace",
  "Workspace của bạn": "Your workspaces",
  "CÙNG NHAU LÀM VIỆC": "WORK BETTER TOGETHER",
  "Cách xem Workspace": "Workspace view",
  "Xem Workspace dạng thẻ": "Workspace cards",
  "Xem Workspace dạng danh sách": "Workspace list",
  "Thời gian": "Date range",
  "Tìm theo tên hoặc mô tả Workspace": "Search workspace names or descriptions",
  "Nhập để tìm kiếm…": "Type to search…",
  "Trạng thái Workspace": "Workspace state",
  "Tất cả trạng thái": "All states",
  "Đang hoạt động": "Active",
  "Đã lưu trữ": "Archived",
  "Từ ngày tạo": "Created from",
  "Đến ngày tạo": "Created through",
  "Xóa bộ lọc": "Clear filters",
  "Làm mới": "Refresh",
  "Lọc quyền Workspace": "Workspace access filter",
  "Tất cả": "All",
  "Tôi quản lý": "Managed by me",
  "Thành viên": "Members",
  "Đang áp dụng bộ lọc": "Filters applied",
  "Từ đầu": "Beginning",
  "Hiện tại": "Now",
  "Ngày bắt đầu phải trước hoặc bằng ngày kết thúc.": "Start date must be on or before end date.",
  "Thử lại": "Retry",
  "Đang tải Workspace…": "Loading workspaces…",
  "Chỉ đọc": "Read-only",
  "Không gian để cùng nhau làm việc.": "A space to work together.",
  "Dự án hoạt động": "Active projects",
  "Tạo": "Created",
  "Xem Workspace": "View workspace",
  "Mở Workspace": "Open workspace",
  "Không có Workspace phù hợp": "No matching workspaces",
  "Bạn chưa có Workspace": "No workspaces yet",
  "Thử thay đổi từ khóa hoặc bộ lọc.": "Try another search or filter.",
  "Tạo Workspace đầu tiên để bắt đầu cùng đội ngũ.": "Create your first workspace to start working with your team.",
  "Tải thêm": "Load more",
  "Tên Workspace": "Workspace name",
  "Tối đa 200 ký tự.": "Up to 200 characters.",
  "Hủy": "Cancel",
  "Đang tạo…": "Creating…",
  "Bỏ Workspace đang tạo?": "Discard this new workspace?",
  "Bỏ tên Workspace chưa lưu?": "Discard the unsaved workspace name?",
  "Đóng form và tải lại để kiểm tra Workspace đã tạo chưa?": "Close this form and reload to check whether the workspace was created?",
  "Đã tạo Workspace.": "Workspace created.",
  "Tên Workspace chưa hợp lệ. Nhập tên có nội dung, không có ký tự điều khiển.": "Enter a non-empty workspace name without control characters.",
  "Chưa rõ yêu cầu tạo đã hoàn tất chưa. Đóng form và tải lại danh sách trước khi tạo lại.": "Creation is unconfirmed. Close the form and reload the list before creating again.",
  "Tổng quan cá nhân hôm nay": "Your overview today",
  "Đến hạn hôm nay": "Due today",
  "Công việc chưa hoàn thành": "Unfinished tasks",
  "Đang quá hạn": "Overdue",
  "Cần kiểm tra và xử lý": "Needs your attention",
  "Thông báo chưa đọc": "Unread notifications",
  "Cập nhật từ nhóm của bạn": "Updates from your team",
  "Việc cần chú ý": "Needs attention",
  "Quá hạn hoặc đến hạn hôm nay · Được giao cho bạn": "Overdue or due today · Assigned to you",
  "Xem công việc →": "View tasks →",
  "Đang tải công việc…": "Loading tasks…",
  "Chưa tải được một phần công việc.": "Some tasks could not be loaded.",
  "Mở Công việc của tôi để thử lại.": "Open My Tasks to retry.",
  "Công việc": "Task",
  "Quá hạn": "Overdue",
  "Hôm nay": "Today",
  "Bạn không có công việc quá hạn hoặc đến hạn hôm nay.": "No overdue tasks or tasks due today.",
  "Thông báo mới": "New notifications",
  "Những cập nhật cần bạn xem.": "Updates for you to review.",
  "Đang tải thông báo…": "Loading notifications…",
  "Chưa tải được thông báo.": "Notifications could not be loaded.",
  "Thử lại trong danh sách thông báo.": "Retry in the notification inbox.",
  "Nội dung không còn khả dụng": "Content is unavailable",
  "Bạn đã xem hết thông báo.": "You are all caught up.",
  "Xem tất cả thông báo →": "View all notifications →",
  "Chưa tải được tổng quan công việc.": "Task overview could not be loaded.",
  "Bạn có": "You have",
  "{count} việc đến hạn hôm nay": "{count} tasks due today",
  "tại {count} Workspace": "across {count} workspaces",
  "Lời mời tham gia {name}": "Invitation to join {name}",
  "{count} người": "{count} people",
  "{count} dự án": "{count} projects",
  "Ở lại": "Stay",
  "Bỏ thay đổi": "Discard changes"
};
export function homeText(value, locale, values = {}) {
  const singular = { '{count} người': '{count} person', '{count} dự án': '{count} project', '{count} việc đến hạn hôm nay': '{count} task due today', 'tại {count} Workspace': 'across {count} workspace' };
  const template = locale === 'en' ? (values.count === 1 && singular[value] ? singular[value] : english[value] ?? translateAuthText(value, locale)) : value;
  return template.replace(/\{(\w+)\}/gu, (match, key) => Object.hasOwn(values, key) ? String(values[key]) : match);
}
