import { homeText } from './home-text.js';
const english = {
  "Tổ chức & Studio của bạn": "Your organizations & studios",
  "Chọn đội ngũ để mở các Workspace bạn có quyền truy cập.": "Choose a team to access its workspaces.",
  "Tạo tổ chức": "Create organization",
  "Làm việc theo nhóm nhỏ?": "Working with a small team?",
  "Vào Workspace trực tiếp, không cần tạo tổ chức.": "Open a workspace directly without creating an organization.",
  "Dự án được chia sẻ": "Shared projects",
  "Truy cập Project được cấp với quyền Guest.": "Open projects shared with you as a Guest.",
  "Tìm tổ chức": "Search organizations",
  "Tên đội ngũ, Studio…": "Team or studio name…",
  "Vai trò trong tổ chức": "Organization role",
  "Chủ sở hữu": "Owner",
  "Quản trị viên": "Admin",
  "Thành viên": "Member",
  "Có quyền truy cập": "Access granted",
  "Đang tải tổ chức…": "Loading organizations…",
  "Đội ngũ của bạn": "Your teams",
  "Vai trò của bạn": "Your role",
  "Xem những Workspace bạn đã được thêm vào.": "View workspaces you have joined.",
  "Điều phối Workspace và công việc của đội ngũ.": "Manage team workspaces and work.",
  "Vào tổ chức": "Open organization",
  "Không có tổ chức phù hợp": "No matching organizations",
  "Bạn chưa tham gia tổ chức": "No organizations yet",
  "Bạn có thể tạo tổ chức hoặc tiếp tục dùng Workspace độc lập.": "Create an organization or keep using standalone workspaces.",
  "Tải thêm tổ chức": "Load more organizations",
  "Tên tổ chức / Studio": "Organization / studio name",
  "Đã tạo tổ chức.": "Organization created.",
  "Bạn sẽ là Chủ sở hữu. Sau khi tạo, bạn có thể thiết lập Workspace cho đội ngũ.": "You will be the Owner. You can then set up team workspaces.",
  "Nội dung tổ chức": "Organization navigation",
  "Thành viên & quyền": "Members & permissions",
  "Tổ chức & Studio": "Organizations & Studios",
  "Tổ chức": "Organization",
  "KHÔNG GIAN CỦA ĐỘI NGŨ": "TEAM WORKSPACE",
  "Workspace trong tổ chức": "Organization workspaces",
  "Chỉ hiển thị Workspace bạn có quyền truy cập.": "Only workspaces you can access are shown.",
  "Đang kiểm tra quyền truy cập hiện tại.": "Checking your current access.",
  "Tìm Workspace trong tổ chức": "Search organization workspaces",
  "Tên hoặc mô tả Workspace…": "Workspace name or description…",
  "Workspace trực thuộc": "Organization workspaces",
  "Không gian để đội ngũ cùng làm việc.": "A space for your team to work together.",
  "Chưa có Workspace hiển thị": "No workspaces to display",
  "Tạo Workspace hoặc thay đổi bộ lọc để tiếp tục.": "Create a workspace or adjust your filters to continue.",
  "Bạn chỉ xem được Workspace đã được thêm vào. Liên hệ quản lý nếu cần quyền truy cập.": "You can only view workspaces you have joined. Contact a manager if you need access.",
  "Tải thêm Workspace": "Load more workspaces",
  "Tạo Workspace trong tổ chức": "Create organization workspace",
  "Đã tạo Workspace trong tổ chức.": "Organization workspace created.",
  "Workspace thuộc {name}. Bạn được thiết lập làm Manager ban đầu; vai trò tổ chức được giữ nguyên.": "This workspace belongs to {name}. You become its initial Manager and keep your organization role.",
  "Bỏ nội dung chưa lưu?": "Discard unsaved changes?",
  "Nhập tên có nội dung, không chứa ký tự xuống dòng hoặc điều khiển.": "Enter a non-empty name without line breaks or control characters.",
  "Đang lưu…": "Saving…",
  "Lưu": "Save",
  "Chưa rõ yêu cầu đã lưu chưa. Đóng form và tải lại dữ liệu trước khi gửi lại.": "The save result is unconfirmed. Close the form and reload before trying again.",
  "Tổ chức không còn khả dụng với quyền hiện tại.": "This organization is unavailable with your current access.",
  "Thao tác này cần quyền Chủ sở hữu hoặc Quản trị viên tổ chức hiện tại. Tải lại để kiểm tra quyền.": "This action requires current organization Owner or Admin access. Reload to check your permissions."
};
export function organizationText(value, locale, values = {}) {
  return homeText(locale === 'en' ? (english[value] ?? value) : value, locale, values);
}
