import { homeText } from './home-text.js';
const english = {
  "Tổ chức & Studio của bạn": "Your organizations & studios",
  "Chọn đội ngũ để mở các Workspace bạn có quyền truy cập.": "Choose a team to access its workspaces.",
  "Tạo tổ chức": "Create organization",
  "Làm việc theo nhóm nhỏ?": "Working with a small team?",
  "Vào Workspace trực tiếp, không cần tạo tổ chức.": "Open a workspace directly without creating an organization.",
  "Dự án được chia sẻ": "Shared projects",
  "Truy cập Project được cấp với quyền Guest.": "Open projects shared with you as a Guest.",
  "Tìm tổ chức": "Search organizations",
  "Tên đội ngũ, Studio…": "Team or studio name…",
  "Vai trò trong tổ chức": "Organization role",
  "Chủ sở hữu": "Owner",
  "Quản trị viên": "Admin",
  "Thành viên": "Member",
  "Có quyền truy cập": "Access granted",
  "Đang tải tổ chức…": "Loading organizations…",
  "Đội ngũ của bạn": "Your teams",
  "Vai trò của bạn": "Your role",
  "Xem những Workspace bạn đã được thêm vào.": "View workspaces you have joined.",
  "Điều phối Workspace và công việc của đội ngũ.": "Manage team workspaces and work.",
  "Vào tổ chức": "Open organization",
  "Không có tổ chức phù hợp": "No matching organizations",
  "Bạn chưa tham gia tổ chức": "No organizations yet",
  "Bạn có thể tạo tổ chức hoặc tiếp tục dùng Workspace độc lập.": "Create an organization or keep using standalone workspaces.",
  "Tải thêm tổ chức": "Load more organizations",
  "Tên tổ chức / Studio": "Organization / studio name",
  "Đã tạo tổ chức.": "Organization created.",
  "Bạn sẽ là Chủ sở hữu. Sau khi tạo, bạn có thể thiết lập Workspace cho đội ngũ.": "You will be the Owner. You can then set up team workspaces.",
  "Nội dung tổ chức": "Organization navigation",
  "Thành viên & quyền": "Members & permissions",
  "Tổ chức & Studio": "Organizations & Studios",
  "Tổ chức": "Organization",
  "KHÔNG GIAN CỦA ĐỘI NGŨ": "TEAM WORKSPACE",
  "Workspace trong tổ chức": "Organization workspaces",
  "Chỉ hiển thị Workspace bạn có quyền truy cập.": "Only workspaces you can access are shown.",
  "Đang kiểm tra quyền truy cập hiện tại.": "Checking your current access.",
  "Tìm Workspace trong tổ chức": "Search organization workspaces",
  "Tên hoặc mô tả Workspace…": "Workspace name or description…",
  "Workspace trực thuộc": "Organization workspaces",
  "Không gian để đội ngũ cùng làm việc.": "A space for your team to work together.",
  "Chưa có Workspace hiển thị": "No workspaces to display",
  "Tạo Workspace hoặc thay đổi bộ lọc để tiếp tục.": "Create a workspace or adjust your filters to continue.",
  "Bạn chỉ xem được Workspace đã được thêm vào. Liên hệ quản lý nếu cần quyền truy cập.": "You can only view workspaces you have joined. Contact a manager if you need access.",
  "Tải thêm Workspace": "Load more workspaces",
  "Tạo Workspace trong tổ chức": "Create organization workspace",
  "Đã tạo Workspace trong tổ chức.": "Organization workspace created.",
  "Workspace thuộc {name}. Bạn được thiết lập làm Manager ban đầu; vai trò tổ chức được giữ nguyên.": "This workspace belongs to {name}. You become its initial Manager and keep your organization role.",
  "Bỏ nội dung chưa lưu?": "Discard unsaved changes?",
  "Nhập tên có nội dung, không chứa ký tự xuống dòng hoặc điều khiển.": "Enter a non-empty name without line breaks or control characters.",
  "Đang lưu…": "Saving…",
  "Lưu": "Save",
  "Chưa rõ yêu cầu đã lưu chưa. Đóng form và tải lại dữ liệu trước khi gửi lại.": "The save result is unconfirmed. Close the form and reload before trying again.",
  "Tổ chức không còn khả dụng với quyền hiện tại.": "This organization is unavailable with your current access.",
  "Thao tác này cần quyền Chủ sở hữu hoặc Quản trị viên tổ chức hiện tại. Tải lại để kiểm tra quyền.": "This action requires current organization Owner or Admin access. Reload to check your permissions."
};
Object.assign(english, {
  "Đang chờ phản hồi": "Awaiting response",
  "Đã tham gia": "Joined",
  "Đã thu hồi": "Revoked",
  "Đã hết hạn": "Expired",
  "Quyền hiện tại không cho phép quản lý lời mời.": "Your current access does not allow invitation management.",
  "Thu hồi lời mời tới {email}? Người nhận sẽ không thể tham gia bằng lời mời này.": "Revoke the invitation to {email}? The recipient will no longer be able to join with it.",
  "Thu hồi lời mời": "Revoke invitation",
  "Thu hồi": "Revoke",
  "Đã thu hồi lời mời.": "Invitation revoked.",
  "Chưa rõ lời mời đã được thu hồi. Tải lại trước khi tiếp tục.": "Revocation is unconfirmed. Reload before continuing.",
  "CÙNG ĐỘI NGŨ LÀM VIỆC": "WORK WITH YOUR TEAM",
  "Đang kiểm tra quyền truy cập.": "Checking access.",
  "Mời thành viên": "Invite member",
  "Thành viên tổ chức chỉ xem Workspace đã được thêm vào. Owner và Admin quản trị các Workspace trực thuộc; Guest được cấp riêng ở từng Project.": "Members only see workspaces they have joined. Owners and Admins manage organization workspaces; Guest access is granted per project.",
  "Danh sách đội ngũ": "Team lists",
  "Lời mời": "Invitations",
  "Nhật ký": "Audit log",
  "Gia nhập mới nhất": "Newest members first",
  "Tìm thành viên": "Search members",
  "Tìm email được mời": "Search invited emails",
  "Tìm theo tên thành viên…": "Member name…",
  "Email người nhận…": "Recipient email…",
  "Trạng thái lời mời": "Invitation state",
  "Từ ngày gia nhập": "Joined from",
  "Từ ngày mời": "Invited from",
  "Đến ngày gia nhập": "Joined through",
  "Đến ngày mời": "Invited through",
  "Đang tải danh sách…": "Loading list…",
  "Đội ngũ của tổ chức": "Organization team",
  "Lời mời tham gia": "Invitations to join",
  "Ngày giờ Việt Nam · Số kết quả theo bộ lọc": "Vietnam time · Filtered result count",
  "Thành viên tổ chức": "Organization members",
  "Lời mời tổ chức": "Organization invitations",
  "Người nhận": "Recipient",
  "Vai trò tổ chức": "Organization role",
  "Trạng thái": "State",
  "Ngày gia nhập": "Joined",
  "Ngày mời / hết hạn": "Invited / expires",
  "Thao tác": "Actions",
  "Hết hạn {date}": "Expires {date}",
  "Phân bổ Workspace cho {name}": "Allocate workspaces for {name}",
  "Đổi vai trò {name}": "Change role for {name}",
  "Chuyển Owner cho {name}": "Transfer ownership to {name}",
  "Vai trò": "Role",
  "Chuyển Owner": "Transfer Owner",
  "Đã kết thúc": "Closed",
  "Không có thành viên phù hợp": "No matching members",
  "Chưa có lời mời phù hợp": "No matching invitations",
  "Thử đổi bộ lọc.": "Try different filters.",
  "Thử đổi bộ lọc hoặc mời thành viên mới.": "Try different filters or invite a new member.",
  "Tải thêm thành viên": "Load more members",
  "Tải thêm lời mời": "Load more invitations",
  "Phạm vi quyền tổ chức": "Organization permission scope",
  "Hiểu đúng phạm vi quyền": "Understand permission scopes",
  "Quản trị tổ chức và Workspace trực thuộc. Chỉ Owner được đổi vai trò Admin và chuyển quyền sở hữu.": "Manage the organization and its workspaces. Only the Owner can change Admin roles or transfer ownership.",
  "Mời thành viên, quản trị Workspace và phân bổ nhân sự. Vai trò quản trị không tự biến thành quyền nhận Task nếu chưa tham gia Workspace.": "Invite members, manage workspaces and allocate people. Management access does not grant task assignment eligibility without workspace membership.",
  "Tham gia Workspace được cấp quyền. Manager và Project Lead là quyền trong phạm vi riêng, không thay vai trò tổ chức.": "Join authorized workspaces. Workspace Manager and Project Lead are scoped roles and do not replace your organization role.",
  "Bỏ lời mời chưa gửi?": "Discard this unsent invitation?",
  "Người này đã là thành viên trong phạm vi đã chọn.": "This person is already a member in the selected scope.",
  "Đã tạo lời mời. Email đang chờ hệ thống gửi.": "Invitation created. Email is queued for delivery.",
  "Chưa rõ lời mời đã được tạo. Đóng form và tải lại danh sách trước khi gửi tiếp.": "Invitation creation is unconfirmed. Close the form and reload before sending again.",
  "Mời vào tổ chức": "Invite to organization",
  "Người nhận sẽ tham gia {name} với vai trò Thành viên. Lời mời chỉ dành cho email này và có hiệu lực 7 ngày.": "The recipient joins {name} as a Member. This invitation is limited to this email and is valid for 7 days.",
  "Email người nhận": "Recipient email",
  "Người nhận cần đăng nhập bằng tài khoản có cùng email đã xác minh.": "The recipient must sign in with the same verified email.",
  "Workspace đích (không bắt buộc)": "Target workspace (optional)",
  "Thêm vào Workspace sau khi người nhận chấp nhận lời mời tổ chức.": "Join the workspace after accepting the organization invitation.",
  "Chỉ tham gia tổ chức": "Organization only",
  "Đang tải Workspace có thể chọn…": "Loading available workspaces…",
  "Tải lại Workspace": "Reload workspaces",
  "Tải thêm Workspace để chọn": "Load more available workspaces",
  "Đang tạo lời mời…": "Creating invitation…",
  "Tạo lời mời": "Create invitation"
});
Object.assign(english, {
  "Đổi vai trò tổ chức": "Change organization role",
  "Chuyển quyền sở hữu tổ chức": "Transfer organization ownership",
  "Phân bổ quyền Workspace": "Allocate workspace access",
  "Bỏ thay đổi quyền chưa lưu?": "Discard unsaved permission changes?",
  "Người này đã tham gia Workspace.": "This person already belongs to the workspace.",
  "Đã chuyển quyền sở hữu tổ chức.": "Organization ownership transferred.",
  "Đã cập nhật vai trò tổ chức.": "Organization role updated.",
  "Đã cập nhật Manager của Workspace.": "Workspace Manager updated.",
  "Đã thêm thành viên vào Workspace.": "Member added to workspace.",
  "Chưa rõ thay đổi quyền đã được lưu. Đóng form và tải lại dữ liệu trước khi gửi tiếp.": "Permission changes are unconfirmed. Close the form and reload before trying again.",
  "Vai trò mới": "New role",
  "Chỉ Owner được thay đổi vai trò Admin; Owner không đổi bằng thao tác này.": "Only the Owner can change Admin roles. This action does not change the Owner.",
  "Admin được quản trị các Workspace trực thuộc. Hạ về Thành viên sẽ thu hồi quyền quản trị toàn tổ chức; các quyền Workspace đã cấp vẫn được xét riêng.": "Admins manage organization workspaces. Demotion to Member removes organization management access; existing workspace access is evaluated separately.",
  "Quyền trong Workspace": "Workspace access",
  "Không thay đổi vai trò tổ chức.": "Your organization role remains unchanged.",
  "Thêm thành viên": "Add member",
  "Bổ nhiệm Manager": "Appoint Manager",
  "Có thể thay Manager ở Workspace lưu trữ để khôi phục người quản lý hợp lệ.": "An archived workspace can receive a valid replacement Manager.",
  "Workspace phải đang hoạt động. Không cần thành viên chấp nhận lại.": "The workspace must be active. The member does not need to accept again.",
  "Chọn Workspace": "Choose workspace",
  " · Đã lưu trữ": " · Archived",
  "Thay Manager hiện tại bằng {name}. Người được chọn được thêm vào Workspace nếu chưa tham gia; Manager trước vẫn là thành viên nếu còn quyền.": "Replace the current Manager with {name}. The new Manager joins the workspace if needed; the previous Manager remains a member if still authorized.",
  "Thêm {name} vào {workspace} ngay lập tức.": "Add {name} to {workspace} immediately.",
  "{name} trở thành Owner mới. Bạn quay về vai trò tổ chức đã có trước khi làm Owner; quyền Workspace/Manager được giữ theo phạm vi riêng.": "{name} becomes the new Owner. Your previous organization role is restored; workspace and Manager access remains scoped separately.",
  "Nhập tên tổ chức để xác nhận": "Type the organization name to confirm",
  "Nhập đúng: {name}": "Type exactly: {name}",
  "Đang cập nhật…": "Updating…",
  "Lưu quyền": "Save permissions",
  "Nhật ký quản trị": "Management audit log",
  "Tải lại nhật ký": "Reload audit log",
  "Mới nhất trước · Tên hiển thị hiện tại, mã tham chiếu lịch sử được giữ.": "Newest first · Current display names; historical reference IDs are preserved.",
  "Đang tải nhật ký…": "Loading audit log…",
  "Thay đổi quản trị": "Management change",
  "Thêm thành viên vào Workspace": "Member added to workspace",
  "Thay Manager": "Manager changed",
  "Chuyển quyền sở hữu": "Ownership transferred",
  "Tham gia tổ chức": "Joined organization",
  "Rời tổ chức": "Left organization",
  "Gỡ thành viên": "Member removed",
  "Người dùng không còn khả dụng": "User unavailable",
  "Xem Workspace liên quan": "View related workspace",
  "Chưa có nhật ký để hiển thị.": "No audit records to display.",
  "Tải thêm nhật ký": "Load more audit records",
  "Dữ liệu đã được người khác thay đổi. Tải lại trước khi lưu tiếp.": "This data changed in another session. Reload before saving again.",
  "Thao tác này cần quyền Chủ sở hữu tổ chức hiện tại.": "This action requires the current organization Owner."
});
export function organizationText(value, locale, values = {}) {
  return homeText(locale === 'en' ? (english[value] ?? value) : value, locale, values);
}
