import { organizationText } from './organization-text.js';
const english = {
  "Trang chủ": "Home",
  "Bỏ thay đổi cài đặt chưa lưu?": "Discard unsaved settings changes?",
  "Tải lại": "Reload",
  "Đã lưu trữ · Chỉ đọc": "Archived · Read-only",
  "Mô tả Workspace": "Workspace description",
  "Chỉnh sửa mô tả Workspace": "Edit workspace description",
  "Mô tả nhóm": "Team description",
  "Workspace chưa có mô tả.": "No workspace description yet.",
  "Thêm mục tiêu và cách làm việc của nhóm trong Cài đặt nhóm.": "Add team goals and ways of working in Workspace settings.",
  "Người quản lý có thể bổ sung mô tả cho nhóm.": "A manager can add a description for the team.",
  "Tạo Dự án": "Create project",
  "Mở lại Workspace": "Reopen workspace",
  "Lưu trữ Workspace": "Archive workspace",
  "Workspace đang lưu trữ. Dự án và Task bên trong chỉ đọc; mở lại Workspace không thay đổi trạng thái riêng của từng Dự án.": "This workspace is archived. Projects and tasks are read-only; reopening it preserves each project’s own state.",
  "Nội dung Workspace": "Workspace sections",
  "Dự án": "Projects",
  "Cài đặt nhóm": "Workspace settings",
  "Email của tôi trong nhóm": "My workspace email preferences",
  "Dự án trong Workspace": "Workspace projects",
  "{count} kết quả": "{count} results",
  "Tìm theo tên hoặc mô tả Dự án": "Search project names or descriptions",
  "Trạng thái Dự án": "Project state",
  "Ngày tạo theo giờ Việt Nam · Tiến độ tính trên toàn Dự án, không gồm Task trong thùng rác": "Created in Vietnam time · Progress covers the whole project and excludes trashed tasks",
  "Đang tải Dự án…": "Loading projects…",
  "Dự án lưu trữ · Chỉ đọc": "Project archived · Read-only",
  "Workspace lưu trữ · Chỉ đọc": "Workspace archived · Read-only",
  "Không gian để biến ý tưởng thành công việc.": "A space to turn ideas into work.",
  "{done}/{total} Task hoàn thành": "{done}/{total} tasks completed",
  "Tiến độ {name}": "Progress for {name}",
  "Xem Dự án": "View project",
  "Vào Bảng Kanban": "Open Kanban board",
  "Sửa tên và biểu tượng {name}": "Edit name and icon for {name}",
  "Chỉnh sửa": "Edit",
  "Không có Dự án phù hợp": "No matching projects",
  "Tạo Dự án đầu tiên hoặc thay đổi bộ lọc để tìm công việc của nhóm.": "Create your first project or adjust filters to find your team’s work.",
  "Thay đổi bộ lọc hoặc liên hệ người quản lý để tạo Dự án.": "Adjust filters or contact a manager to create a project.",
  "Chỉnh sửa Dự án": "Edit project",
  "Tên Dự án": "Project name",
  "Đã cập nhật Dự án.": "Project updated.",
  "Đã tạo Dự án.": "Project created.",
  "Bỏ xác nhận chưa gửi?": "Discard this unsent confirmation?",
  "Nhập đúng tên Workspace và lý do để tiếp tục.": "Enter the exact workspace name and a reason to continue.",
  "Đã mở lại Workspace.": "Workspace reopened.",
  "Đã lưu trữ Workspace.": "Workspace archived.",
  "Chưa rõ trạng thái đã được cập nhật. Đóng hộp thoại và tải lại để kiểm tra trước khi gửi tiếp.": "The state change is unconfirmed. Close the dialog and reload before trying again.",
  "Workspace hoạt động trở lại. Dự án đã lưu trữ riêng vẫn giữ nguyên trạng thái.": "The workspace becomes active again. Separately archived projects retain their state.",
  "Các Dự án và Task bên trong chuyển sang chỉ đọc. Dữ liệu được giữ lại và có thể mở Workspace sau.": "Projects and tasks become read-only. Data is retained and the workspace can be reopened later.",
  "Nhập lại tên Workspace": "Type the workspace name again",
  "Phải khớp chính xác tên ở trên.": "It must match the name above exactly.",
  "Lý do": "Reason",
  "Được ghi vào nhật ký. Tối đa 2.000 ký tự.": "Recorded in the audit log. Up to 2,000 characters.",
  "Thu gọn mô tả": "Collapse description",
  "Đọc toàn bộ mô tả": "Read full description",
  "Cuộn trong khung để đọc toàn bộ nội dung.": "Scroll within the panel to read the full description.",
  "{name} — nội dung đầy đủ": "{name} — full content",
  "Biểu tượng Dự án": "Project icon",
  "Chung": "General",
  "Thiết kế": "Design",
  "Kỹ thuật": "Engineering",
  "Tài liệu": "Documents",
  "Đang tải trình soạn thảo…": "Loading editor…",
  "Workspace đang lưu trữ và chỉ đọc. Quản lý cần mở lại trước khi thay đổi dữ liệu.": "This workspace is archived and read-only. A manager must reopen it before changes.",
  "Tên xác nhận chưa khớp tên Workspace hiện tại.": "The confirmation name does not match the current workspace name.",
  "Cần bổ nhiệm Manager còn quyền hợp lệ trước khi mở lại Workspace.": "Appoint a valid Manager before reopening this workspace."
};
Object.assign(english, {
  "Bộ lọc": "Filters",
  "Hiệu lực": "Validity",
  "Liên kết": "Link",
  "Từ ngày tạo": "Created from",
  "Đến ngày tạo": "Created until",
  "Từ ngày gia nhập": "Joined from",
  "Đến ngày gia nhập": "Joined until",
  "Đang xử lý yêu cầu. Vui lòng chờ kết quả trước khi rời trang.": "A request is in progress. Wait for the result before leaving this page.",
  "Bỏ thay đổi chưa lưu và tải lại cài đặt Workspace?": "Discard unsaved changes and reload workspace settings?",
  "Tên tối đa 200 ký tự, không để trống hoặc chứa ký tự điều khiển.": "Enter a non-empty name of up to 200 characters without control characters.",
  "Mô tả tối đa 20.000 ký tự hiển thị.": "Description is limited to 20,000 displayed characters.",
  "Đã trở về cài đặt chung.": "Account settings restored.",
  "Đã lưu cài đặt.": "Settings saved.",
  "Đã lưu cài đặt Workspace.": "Workspace settings saved.",
  "Chưa xác nhận đã lưu. Tải lại cài đặt để kiểm tra trước khi gửi tiếp.": "Saving is unconfirmed. Reload settings before submitting again.",
  "Cài đặt Workspace": "Workspace settings",
  "Tải lại cài đặt": "Reload settings",
  "Đang tải cài đặt…": "Loading settings…",
  "Tùy chọn email riêng chỉ dành cho thành viên của Workspace.": "Workspace email preferences are only available to its members.",
  "Workspace đang lưu trữ. Mở lại trước khi sửa tên hoặc mô tả.": "This workspace is archived. Reopen it before editing its name or description.",
  "Chỉ người quản lý hiện tại được sửa thông tin nhóm.": "Only a current manager can edit workspace information.",
  "Các lựa chọn này chỉ áp dụng cho bạn trong {name}. Email xác minh và bảo mật không bị tắt.": "These choices only apply to you in {name}. Verification and security emails remain enabled.",
  "Phân công Task": "Task assignment",
  "Bình luận mới": "New comments",
  "Nội dung hoặc deadline thay đổi": "Content or deadline changes",
  "Trạng thái Task thay đổi": "Task status changes",
  "Theo cài đặt chung": "Use account settings",
  "Bật": "On",
  "Tắt": "Off",
  "Hiện tại:": "Effective:",
  " · Kế thừa tài khoản": " · Inherited from account",
  " · Riêng Workspace này": " · Workspace override",
  "Rời nhóm sẽ xóa các tùy chọn riêng. Gia nhập lại sẽ theo cài đặt chung.": "Leaving removes these overrides. Rejoining uses your account settings.",
  "Mở cài đặt email chung": "Open account email settings",
  "Tên và mô tả được chia sẻ với các thành viên trong nhóm.": "The name and description are shared with workspace members.",
  "Trở về cài đặt chung": "Reset to account settings",
  "Hủy thay đổi": "Discard changes",
  "Lưu cài đặt": "Save settings",
  "Đường dẫn https:// hoặc mailto: (để trống để bỏ liên kết)": "Enter an https:// or mailto: URL (leave blank to remove the link)",
  "Liên kết chưa hợp lệ.": "Invalid link.",
  "Định dạng {name}": "Format {name}",
  "Đậm": "Bold",
  "Nghiêng": "Italic",
  "Gạch chân": "Underline",
  "Tiêu đề 1": "Heading 1",
  "Tiêu đề 2": "Heading 2",
  "Văn bản thường": "Body text",
  "Nội dung": "Body text",
  "Danh sách dấu đầu dòng": "Bullet list",
  "Danh sách đánh số": "Numbered list",
  "Chèn hoặc sửa liên kết": "Insert or edit link",
  "Thêm emoji": "Insert emoji",
  "Hoàn tác": "Undo",
  "Làm lại": "Redo",
  "{words} từ · {chars}/{limit} ký tự": "{words} words · {chars}/{limit} characters"
});
Object.assign(english, {"Đưa cả bốn loại email về kế thừa cài đặt chung của bạn?": "Reset all four email types to inherit your account settings?"});
Object.assign(english, {
  "Còn hiệu lực": "Active",
  "Hết hạn": "Expired",
  "Đã nhận": "Accepted",
  "Chờ gửi": "Queued",
  "Đang gửi": "Sending",
  "Dịch vụ gửi đã nhận": "Accepted by mail service",
  "Gửi thất bại": "Delivery failed",
  "Đã hủy gửi": "Delivery cancelled",
  "Thành viên trong nhóm": "Workspace members",
  "Làm mới danh sách": "Refresh list",
  "+ Tạo lời mời": "+ Create invitation",
  "Thêm thành viên nội bộ": "Add organization member",
  "Lời mời chỉ được tạo bởi Owner của Workspace độc lập đang hoạt động. Workspace thuộc tổ chức dùng luồng phân bổ thành viên của tổ chức.": "Only an active standalone Workspace Owner can create invitations. Organization workspaces use internal member allocation.",
  "Mới tham gia trước": "Newest members first",
  "Tìm email người nhận": "Search recipient emails",
  "Tìm tên thành viên": "Search member names",
  "Loại lời mời": "Invitation type",
  "Cách mời": "Invitation method",
  "Qua email": "By email",
  "Qua liên kết": "By link",
  "Mới tạo trước · Thời gian Việt Nam · Tìm kiếm trên toàn danh sách có quyền xem": "Newest first · Vietnam time · Search covers the authorized list",
  "Mới gia nhập trước · Thời gian Việt Nam · Tìm kiếm trên toàn danh sách có quyền xem": "Newest members first · Vietnam time · Search covers the authorized list",
  "Lời mời Workspace": "Workspace invitations",
  "Thành viên Workspace": "Workspace members",
  "Người nhận / loại": "Recipient / type",
  "Vai trò Workspace": "Workspace role",
  "Ngày tạo / hết hạn": "Created / expires",
  "Liên kết tham gia": "Invitation link",
  "Email: {state}": "Email: {state}",
  "Hết hạn {date}": "Expires {date}",
  "Thử gửi lại email": "Retry email delivery",
  "Gỡ khỏi nhóm": "Remove from workspace",
  "Chặn truy cập": "Ban access",
  "Chuyển quyền sở hữu": "Transfer ownership",
  "Không có lời mời phù hợp.": "No matching invitations.",
  "Không có thành viên phù hợp.": "No matching members.",
  "Tư cách thành viên của bạn": "Your membership",
  "Owner cần chuyển quyền sở hữu, Manager cần được thay thế trước khi rời. Quản trị tổ chức chưa tham gia Workspace không có membership để rời.": "An Owner must transfer ownership and a Manager must be replaced before leaving. Organization management access alone is not a workspace membership.",
  "Rời nhóm sẽ mất quyền truy cập Workspace và đưa tùy chọn email riêng về mặc định.": "Leaving removes workspace access and resets your email overrides.",
  "Rời Workspace": "Leave workspace",
  "Bỏ lời mời đang soạn?": "Discard this unsent invitation?",
  "Bỏ xác nhận chuyển quyền sở hữu chưa gửi?": "Discard this unsubmitted ownership transfer confirmation?",
  "Loại thành viên": "Remove member",
  "Người này sẽ mất quyền truy cập. Task chưa Done bị bỏ assignee, kể cả trong Project Archived; Task Done giữ người cũ. Task và bình luận không bị xóa. Gỡ khỏi nhóm không chặn dùng lại lời mời còn hiệu lực.": "This member loses access. Unfinished tasks lose their assignee, including in archived projects; completed tasks keep attribution. Tasks and comments are retained. Removal does not block rejoining with a valid invitation.",
  "Người này sẽ trở thành Owner; bạn trở thành Member và mất quyền quản lý nhóm/lời mời. Bạn vẫn ở trong nhóm, lời mời còn hiệu lực được giữ.": "This person becomes Owner. You become a Member and lose workspace/invitation management access. You stay in the workspace and valid invitations are retained.",
  "Bạn sẽ mất quyền truy cập. Task chưa Done bị bỏ assignee; Task Done giữ người cũ. Tùy chọn email riêng được xóa.": "You lose access. Unfinished tasks lose their assignee; completed tasks retain attribution. Your email overrides are removed.",
  "Ngăn gia nhập qua lời mời này về sau; không loại người đã tham gia và không rút email đã gửi.": "Prevent future use of this invitation. Existing members remain; already sent email cannot be recalled.",
  "Chỉ xếp hàng gửi lại email thất bại; thời hạn lời mời giữ nguyên.": "Queue a retry for failed email delivery only. Invitation expiry is unchanged.",
  "Chưa xác nhận được kết quả. Đóng và làm mới danh sách trước khi thao tác lại.": "The outcome is unconfirmed. Close and refresh the list before trying again.",
  "Người này đã ở trong nhóm.": "This person is already a member.",
  "Đã tạo liên kết. Sao chép trước khi đóng; danh sách không lưu lại URL.": "Invitation link created. Copy it before closing; the list does not retain the URL.",
  "Đã tạo lời mời; email đang chờ gửi.": "Invitation created; email is queued.",
  "Hết hạn {date}. Ai có link hợp lệ và tài khoản đã xác minh đều có thể tham gia.": "Expires {date}. Anyone with a valid link and a verified account can join.",
  "Đã sao chép.": "Copied.",
  "Chọn liên kết để sao chép thủ công.": "Select the link to copy it manually.",
  "Sao chép liên kết": "Copy link",
  "Đóng kết quả": "Close result",
  "Lời mời có hạn 7 ngày. Chỉ tài khoản đã xác minh được gia nhập.": "Invitations are valid for 7 days. Only verified accounts can join.",
  "Nhập tên Workspace để xác nhận": "Type the workspace name to confirm",
  "Đóng": "Close",
  "Bỏ lựa chọn thành viên chưa thêm?": "Discard the unsubmitted member selection?",
  "Chưa xác nhận kết quả. Đóng và tải lại trước khi thêm tiếp.": "The outcome is unconfirmed. Close and reload before adding again.",
  "Chọn thành viên đang trong tổ chức để thêm ngay vào {name}, không cần chấp nhận lại.": "Add an active organization member to {name} immediately, without another acceptance step.",
  "Tìm thành viên tổ chức": "Search organization members",
  "Thành viên được thêm": "Member to add",
  "Chọn thành viên": "Choose member",
  "Đang tải thành viên…": "Loading members…",
  "Tải thêm thành viên để chọn": "Load more available members",
  "Tải lại thành viên": "Reload members",
  "Thêm vào Workspace": "Add to workspace",
  "Workspace không còn khả dụng với quyền hiện tại.": "This workspace is unavailable with your current access."
});
export function workspaceText(value, locale, values = {}) {
  return organizationText(locale === 'en' ? (english[value] ?? value) : value, locale, values);
}
