import { organizationText } from './organization-text.js';
const english = {
  "Bỏ thay đổi cài đặt chưa lưu?": "Discard unsaved settings changes?",
  "Tải lại": "Reload",
  "Đã lưu trữ · Chỉ đọc": "Archived · Read-only",
  "Mô tả Workspace": "Workspace description",
  "Chỉnh sửa mô tả Workspace": "Edit workspace description",
  "Mô tả nhóm": "Team description",
  "Workspace chưa có mô tả.": "No workspace description yet.",
  "Thêm mục tiêu và cách làm việc của nhóm trong Cài đặt nhóm.": "Add team goals and ways of working in Workspace settings.",
  "Người quản lý có thể bổ sung mô tả cho nhóm.": "A manager can add a description for the team.",
  "Tạo Dự án": "Create project",
  "Mở lại Workspace": "Reopen workspace",
  "Lưu trữ Workspace": "Archive workspace",
  "Workspace đang lưu trữ. Dự án và Task bên trong chỉ đọc; mở lại Workspace không thay đổi trạng thái riêng của từng Dự án.": "This workspace is archived. Projects and tasks are read-only; reopening it preserves each project’s own state.",
  "Nội dung Workspace": "Workspace sections",
  "Dự án": "Projects",
  "Cài đặt nhóm": "Workspace settings",
  "Email của tôi trong nhóm": "My workspace email preferences",
  "Dự án trong Workspace": "Workspace projects",
  "{count} kết quả": "{count} results",
  "Tìm theo tên hoặc mô tả Dự án": "Search project names or descriptions",
  "Trạng thái Dự án": "Project state",
  "Ngày tạo theo giờ Việt Nam · Tiến độ tính trên toàn Dự án, không gồm Task trong thùng rác": "Created in Vietnam time · Progress covers the whole project and excludes trashed tasks",
  "Đang tải Dự án…": "Loading projects…",
  "Dự án lưu trữ · Chỉ đọc": "Project archived · Read-only",
  "Workspace lưu trữ · Chỉ đọc": "Workspace archived · Read-only",
  "Không gian để biến ý tưởng thành công việc.": "A space to turn ideas into work.",
  "{done}/{total} Task hoàn thành": "{done}/{total} tasks completed",
  "Tiến độ {name}": "Progress for {name}",
  "Xem Dự án": "View project",
  "Vào Bảng Kanban": "Open Kanban board",
  "Sửa tên và biểu tượng {name}": "Edit name and icon for {name}",
  "Chỉnh sửa": "Edit",
  "Không có Dự án phù hợp": "No matching projects",
  "Tạo Dự án đầu tiên hoặc thay đổi bộ lọc để tìm công việc của nhóm.": "Create your first project or adjust filters to find your team’s work.",
  "Thay đổi bộ lọc hoặc liên hệ người quản lý để tạo Dự án.": "Adjust filters or contact a manager to create a project.",
  "Chỉnh sửa Dự án": "Edit project",
  "Tên Dự án": "Project name",
  "Đã cập nhật Dự án.": "Project updated.",
  "Đã tạo Dự án.": "Project created.",
  "Bỏ xác nhận chưa gửi?": "Discard this unsent confirmation?",
  "Nhập đúng tên Workspace và lý do để tiếp tục.": "Enter the exact workspace name and a reason to continue.",
  "Đã mở lại Workspace.": "Workspace reopened.",
  "Đã lưu trữ Workspace.": "Workspace archived.",
  "Chưa rõ trạng thái đã được cập nhật. Đóng hộp thoại và tải lại để kiểm tra trước khi gửi tiếp.": "The state change is unconfirmed. Close the dialog and reload before trying again.",
  "Workspace hoạt động trở lại. Dự án đã lưu trữ riêng vẫn giữ nguyên trạng thái.": "The workspace becomes active again. Separately archived projects retain their state.",
  "Các Dự án và Task bên trong chuyển sang chỉ đọc. Dữ liệu được giữ lại và có thể mở Workspace sau.": "Projects and tasks become read-only. Data is retained and the workspace can be reopened later.",
  "Nhập lại tên Workspace": "Type the workspace name again",
  "Phải khớp chính xác tên ở trên.": "It must match the name above exactly.",
  "Lý do": "Reason",
  "Được ghi vào nhật ký. Tối đa 2.000 ký tự.": "Recorded in the audit log. Up to 2,000 characters.",
  "Thu gọn mô tả": "Collapse description",
  "Đọc toàn bộ mô tả": "Read full description",
  "Cuộn trong khung để đọc toàn bộ nội dung.": "Scroll within the panel to read the full description.",
  "{name} — nội dung đầy đủ": "{name} — full content",
  "Biểu tượng Dự án": "Project icon",
  "Chung": "General",
  "Thiết kế": "Design",
  "Kỹ thuật": "Engineering",
  "Tài liệu": "Documents",
  "Đang tải trình soạn thảo…": "Loading editor…",
  "Workspace đang lưu trữ và chỉ đọc. Quản lý cần mở lại trước khi thay đổi dữ liệu.": "This workspace is archived and read-only. A manager must reopen it before changes.",
  "Tên xác nhận chưa khớp tên Workspace hiện tại.": "The confirmation name does not match the current workspace name.",
  "Cần bổ nhiệm Manager còn quyền hợp lệ trước khi mở lại Workspace.": "Appoint a valid Manager before reopening this workspace."
};
export function workspaceText(value, locale, values = {}) {
  return organizationText(locale === 'en' ? (english[value] ?? value) : value, locale, values);
}
