import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { once } from 'node:events';
import mongoose from 'mongoose';
import { connectDatabase } from '../src/database.js';
import { models, User, Session, Organization, OrganizationMembership, OrganizationAudit, Workspace, WorkspaceMembership, Project, Task, TaskComment, Notification, EmailOutbox } from '../src/models/index.js';
import { createOrganizationService } from '../src/organizations/service.js';
import { createMongoOrganizationStore } from '../src/organizations/mongo-store.js';
import { createApp } from '../src/app.js';
import { createWorkService } from '../src/work/service.js';
import { createMongoWorkStore } from '../src/work/mongo-store.js';
import { createWorkspaceService } from '../src/workspaces/service.js';
import { createMongoWorkspaceStore } from '../src/workspaces/mongo-store.js';
import { testConfig } from '../test-support/auth-store.js';
import { cutoffCodec } from '../src/notifications/input.js';
import { createNotificationsService } from '../src/notifications/service.js';
import { createMongoNotificationsStore } from '../src/notifications/mongo-store.js';
import { dispatchWorkMail } from '../src/mail/work-mail.js';
import { auditOrganizationScope } from '../src/organizations/scope-audit.js';

test('Organization transactional scope and HTTP on isolated MongoDB', { skip: !process.env.TEST_MONGODB_URI, timeout: 90_000 }, async t => {
  assert.equal(new URL(process.env.TEST_MONGODB_URI).pathname.slice(1), 'workflow_auth_test');
  await connectDatabase(process.env.TEST_MONGODB_URI);
  const users = [], sessions = [], identities = [], organizations = [], workspaceIds = [];
  let server;
  const service = createOrganizationService({ store: createMongoOrganizationStore() });
  try {
    for (const model of Object.values(models)) await model.createIndexes();
    for (let i = 0; i < 5; i++) {
      const user = new User({ displayName: `Org test ${i}`, email: `${randomUUID()}@example.com`,
        emailVerifiedAt: i === 3 ? null : new Date(), termsAcceptance: { version: 'test', acceptedAt: new Date() } });
      await user.save(); users.push(user);
      const session = new Session({ userId: user._id, refreshTokenHash: String(i + 1).repeat(64),
        expiresAt: new Date(Date.now() + 60_000), lastSeenAt: new Date(), authVersionAtIssue: 0 });
      await session.save(); sessions.push(session);
      identities.push({ claims: { sub: String(user._id), sid: String(session._id), av: 0 } });
    }
    const create = async (actor, name) => {
      const result = await service.create(identities[actor], { name });
      organizations.push(new mongoose.Types.ObjectId(result.organization.id));
      return result.organization;
    };
    const first = await create(0, 'Studio One');
    const second = await create(1, 'Studio Two');
    await t.test('atomic owner membership, bounded list and cross-organization privacy', async () => {
      assert.equal(first.role, 'owner');
      assert.equal((await OrganizationMembership.collection.findOne({ organizationId: organizations[0], userId: users[0]._id })).role, 'member');
      assert.deepEqual((await service.list(identities[0], {})).items.map(x => x.id), [first.id]);
      await assert.rejects(service.get(identities[0], second.id), { code: 'ORGANIZATION_UNAVAILABLE' });
      await assert.rejects(service.get(identities[2], first.id), { code: 'ORGANIZATION_UNAVAILABLE' });
      await assert.rejects(new OrganizationMembership({ organizationId: organizations[0], userId: users[0]._id, joinedAt: new Date() }).save(), error => error.code === 11000);
      const third = await create(0, 'Studio Three');
      const page = await service.list(identities[0], { limit: '1' });
      assert.equal(page.items[0].id, third.id);
      assert.ok(page.nextCursor);
      const next = await service.list(identities[0], { limit: '1', cursor: page.nextCursor });
      assert.equal(next.items[0].id, first.id);
    });
    await new OrganizationMembership({ organizationId: organizations[0], userId: users[2]._id, joinedAt: new Date() }).save();
    await t.test('member reads but cannot manage; current admin can manage and demotion takes effect', async () => {
      assert.equal((await service.get(identities[2], first.id)).organization.role, 'member');
      await assert.rejects(service.update(identities[2], first.id, { name: 'Forbidden', expectedVersion: 0 }), { code: 'ORGANIZATION_ADMIN_REQUIRED' });
      await OrganizationMembership.collection.updateOne({ organizationId: organizations[0], userId: users[2]._id }, { $set: { role: 'admin' } });
      const updated = await service.update(identities[2], first.id, { name: 'Updated', expectedVersion: 0 });
      assert.equal(updated.organization.role, 'admin');
      assert.equal(updated.organization.version, 1);
      await OrganizationMembership.collection.updateOne({ organizationId: organizations[0], userId: users[2]._id }, { $set: { role: 'member' } });
      await assert.rejects(service.update(identities[2], first.id, { name: 'No longer allowed', expectedVersion: 1 }), { code: 'ORGANIZATION_ADMIN_REQUIRED' });
    });
    await t.test('concurrent CAS accepts only one edit and hides internal revision', async () => {
      const results = await Promise.allSettled(['A', 'B'].map(name => service.update(identities[0], first.id, { name, expectedVersion: 1 })));
      assert.equal(results.filter(x => x.status === 'fulfilled').length, 1);
      assert.equal(results.find(x => x.status === 'rejected').reason.code, 'VERSION_CONFLICT');
      assert.equal(Object.hasOwn((await service.get(identities[0], first.id)).organization, 'mutationRevision'), false);
    });
    await t.test('membership revocation, stale auth version and unverified user are denied at store', async () => {
      await OrganizationMembership.collection.updateOne({ organizationId: organizations[0], userId: users[2]._id }, { $set: { state: 'inactive', leftAt: new Date() } });
      await assert.rejects(service.get(identities[2], first.id), { code: 'ORGANIZATION_UNAVAILABLE' });
      assert.deepEqual((await service.list(identities[2], {})).items, []);
      await assert.rejects(service.create(identities[3], { name: 'Not verified' }), { code: 'EMAIL_VERIFICATION_REQUIRED' });
      await assert.rejects(service.list({ claims: { ...identities[0].claims, av: 999 } }, {}), { code: 'UNAUTHENTICATED' });
    });
    await t.test('HTTP requires authentication/origin and rejects role injection; scoped DTO works', async () => {
      const authService = { authenticate: async token => {
        if (token !== 'fixture') throw Object.assign(new Error(), {});
        return identities[0];
      } };
      const app = createApp({ authService, authConfig: { webOrigin: 'http://localhost:5173' }, organizationService: service });
      server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
      const base = `http://127.0.0.1:${server.address().port}/organizations`;
      assert.equal((await fetch(base)).status, 401);
      const headers = { authorization: 'Bearer fixture', origin: 'http://localhost:5173', 'content-type': 'application/json' };
      assert.equal((await fetch(base, { method: 'POST', headers: { ...headers, origin: 'http://evil.example' }, body: '{"name":"X"}' })).status, 403);
      assert.equal((await fetch(base, { method: 'POST', headers, body: '{"name":"X","role":"admin"}' })).status, 400);
      const result = await fetch(`${base}/${first.id}`, { headers });
      assert.equal(result.status, 200);
      assert.equal((await result.json()).organization.role, 'owner');
      const made = await fetch(base, { method: 'POST', headers, body: '{"name":"HTTP Studio"}' });
      assert.equal(made.status, 201);
      organizations.push(new mongoose.Types.ObjectId((await made.json()).organization.id));
    });
    await t.test('attached Workspace access covers Admin/Manager, work, inbox/mail and independent scope', async () => {
      const config = testConfig();
      const workspaceService = createWorkspaceService({ store: createMongoWorkspaceStore({ config }) });
      const work = createWorkService({ store: createMongoWorkStore() });
      const cutoff = cutoffCodec(config.accessKeyHex);
      const inbox = createNotificationsService({ store: createMongoNotificationsStore({ cutoff }), cutoff });
      await new OrganizationMembership({ organizationId: organizations[0], userId: users[1]._id, role: 'admin', joinedAt: new Date() }).save();
      await OrganizationMembership.collection.updateOne({ organizationId: organizations[0], userId: users[2]._id }, { $set: { state: 'active', leftAt: null } });
      await assert.rejects(service.createWorkspace(identities[2], first.id, { name: 'Denied' }), { code: 'ORGANIZATION_ADMIN_REQUIRED' });
      assert.throws(() => service.createWorkspace(identities[0], first.id, { name: 'Injected', organizationId: second.id }));
      const attached = (await service.createWorkspace(identities[0], first.id, { name: 'Design' })).workspace;
      workspaceIds.push(new mongoose.Types.ObjectId(attached.id));
      assert.equal(attached.ownerId, null); assert.equal(attached.managerId, String(users[0]._id));
      const managed = (await workspaceService.get(identities[1], attached.id)).workspace;
      assert.equal(managed.role, 'organization_admin'); assert.equal(managed.membershipVersion, null);
      assert.equal((await service.workspaces(identities[1], first.id, {})).items.length, 1);
      assert.equal((await service.workspaces(identities[2], first.id, {})).items.length, 0);
      assert.ok((await workspaceService.list(identities[1], {})).items.some(x => x.id === attached.id));
      const base = `http://127.0.0.1:${server.address().port}/organizations/${first.id}/workspaces`;
      const headers = { authorization: 'Bearer fixture', origin: 'http://localhost:5173', 'content-type': 'application/json' };
      assert.equal((await fetch(base, { headers })).status, 200);
      assert.equal((await fetch(base, { method: 'POST', headers, body: JSON.stringify({ name: 'Spoof', managerId: String(users[2]._id) }) })).status, 400);
      const made = await fetch(base, { method: 'POST', headers, body: JSON.stringify({ name: 'HTTP Attached' }) });
      assert.equal(made.status, 201);
      workspaceIds.push(new mongoose.Types.ObjectId((await made.json()).workspace.id));
      await assert.rejects(workspaceService.get(identities[2], attached.id), { code: 'WORKSPACE_UNAVAILABLE' });
      await assert.rejects(workspaceService.overrides(identities[1], attached.id, { expectedVersion: 0, emailOverrides: { assignment: 'off' } }), { code: 'WORKSPACE_MEMBERSHIP_REQUIRED' });
      await assert.rejects(workspaceService.transfer(identities[1], attached.id, { expectedVersion: 0, memberId: String(users[2]._id) }), { code: 'ORGANIZATION_OWNERSHIP_REQUIRED' });
      await assert.rejects(workspaceService.invite(identities[1], attached.id, { type: 'LINK' }), { code: 'ORGANIZATION_INVITATION_REQUIRED' });
      const project = (await work.createProject(identities[1], attached.id, { name: 'Bloom' })).project;
      assert.equal((await work.profile(identities[0], project.id, String(users[1]._id))).profile.status, 'organization_management');
      await assert.rejects(work.createTask(identities[1], project.id, { title: 'Bad assignee', assigneeId: String(users[1]._id) }), { code: 'ASSIGNEE_NOT_MEMBER' });
      await new WorkspaceMembership({ workspaceId: workspaceIds[0], userId: users[2]._id, joinedAt: new Date() }).save();
      const task = (await work.createTask(identities[0], project.id, { title: 'Design checkout', assigneeId: String(users[2]._id) })).task;
      assert.equal((await work.getTask(identities[1], task.id)).task.permissions.edit, true);
      assert.equal((await work.mine(identities[2], {})).total, 1);
      await Workspace.collection.updateOne({ _id: workspaceIds[0] }, { $set: { managerId: users[2]._id } });
      assert.equal((await workspaceService.get(identities[2], attached.id)).workspace.role, 'manager');
      assert.equal((await work.getTask(identities[2], task.id)).task.permissions.edit, true);
      await work.status(identities[0], task.id, { status: 'done', expectedVersion: 0 });
      await assert.rejects(workspaceService.leave(identities[2], attached.id, { expectedVersion: 0 }), { code: 'MANAGER_REPLACEMENT_REQUIRED' });
      // Revoking organization membership must deny stale Workspace membership, counts and deliveries.
      await OrganizationMembership.collection.updateOne({ organizationId: organizations[0], userId: users[2]._id }, { $set: { state: 'inactive', leftAt: new Date() } });
      await assert.rejects(work.getTask(identities[2], task.id), { code: 'RESOURCE_UNAVAILABLE' });
      assert.equal((await work.mine(identities[2], {})).total, 0);
      assert.equal((await workspaceService.list(identities[2], {})).items.length, 0);
      assert.equal((await work.getTask(identities[0], task.id)).task.assigneeLeft, true);
      const home = await workspaceService.list(identities[0], {});
      assert.equal(home.items.find(x => x.id === attached.id).memberCount, 1);
      assert.equal((await workspaceService.members(identities[0], attached.id, {})).items.length, 1);
      const reopened = await work.status(identities[0], task.id, { status: 'in_progress', expectedVersion: 1, reason: 'Kiểm tra lại' });
      assert.equal(reopened.task.assigneeId, null);
      assert.equal((await inbox.list(identities[2], {})).items[0].available, false);
      let delivered = 0;
      assert.equal((await dispatchWorkMail({ config, send: async () => { delivered++; return 'capture'; } })).state, 'cancelled');
      assert.equal(delivered, 0);
      const standalone = (await workspaceService.create(identities[2], { name: 'Independent' })).workspace;
      workspaceIds.push(new mongoose.Types.ObjectId(standalone.id));
      assert.equal(standalone.organizationId, null);
      await assert.rejects(workspaceService.get(identities[1], standalone.id), { code: 'WORKSPACE_UNAVAILABLE' });
      await assert.rejects(work.createProject(identities[1], standalone.id, { name: 'Cross-scope' }), { code: 'RESOURCE_UNAVAILABLE' });
      const oldWorkspace = { _id: new mongoose.Types.ObjectId(), ownerId: users[2]._id, name: 'Legacy missing fields',
        description: attached.description, version: 0, mutationRevision: 0, createdAt: new Date(), updatedAt: new Date() };
      await Workspace.collection.insertOne(oldWorkspace); workspaceIds.push(oldWorkspace._id);
      await new WorkspaceMembership({ workspaceId: oldWorkspace._id, userId: users[2]._id, joinedAt: new Date() }).save();
      assert.equal((await workspaceService.get(identities[2], String(oldWorkspace._id))).workspace.role, 'owner');
      assert.ok((await workspaceService.list(identities[2], {})).items.some(x => x.id === String(oldWorkspace._id)));
      const demoted = (await workspaceService.update(identities[1], attached.id, { name: 'Admin update', expectedVersion: 0 })).workspace;
      assert.equal(demoted.version, 1);
      await OrganizationMembership.collection.updateOne({ organizationId: organizations[0], userId: users[1]._id }, { $set: { role: 'member' } });
      await assert.rejects(workspaceService.get(identities[1], attached.id), { code: 'WORKSPACE_UNAVAILABLE' });
    });
    await t.test('management API preserves layered roles, logs changes and notifies assigned members', async () => {
      const config = testConfig();
      const cutoff = cutoffCodec(config.accessKeyHex);
      const inbox = createNotificationsService({ store: createMongoNotificationsStore({ cutoff }), cutoff });
      const wsService = createWorkspaceService({ store: createMongoWorkspaceStore({ config }) });
      const work = createWorkService({ store: createMongoWorkStore() });
      const managedOrg = await create(0, 'Management Studio');
      const orgId = new mongoose.Types.ObjectId(managedOrg.id);
      for (const index of [1, 2, 3]) await new OrganizationMembership({ organizationId: orgId, userId: users[index]._id, joinedAt: new Date() }).save();
      const target = index => String(users[index]._id);
      assert.equal((await service.members(identities[0], managedOrg.id, { q: 'Org test 2' })).items.length, 1);
      assert.ok(!(await service.members(identities[0], managedOrg.id, {})).items.some(x => 'email' in x));
      await assert.rejects(service.role(identities[2], managedOrg.id, target(2), { role: 'admin', expectedVersion: 0 }), { code: 'ORGANIZATION_OWNER_REQUIRED' });
      await assert.rejects(service.role(identities[0], managedOrg.id, target(0), { role: 'member', expectedVersion: 0 }), { code: 'OWNER_ROLE_IMMUTABLE' });
      const admin = await service.role(identities[0], managedOrg.id, target(1), { role: 'admin', expectedVersion: 0 });
      assert.equal(admin.version, 1);
      await assert.rejects(service.role(identities[1], managedOrg.id, target(2), { role: 'admin', expectedVersion: 0 }), { code: 'ORGANIZATION_OWNER_REQUIRED' });
      const workspace = (await service.createWorkspace(identities[0], managedOrg.id, { name: 'Delivery' })).workspace;
      const workspaceId = new mongoose.Types.ObjectId(workspace.id); workspaceIds.push(workspaceId);
      const self = await service.manager(identities[1], managedOrg.id, workspace.id, { managerId: target(1), expectedVersion: 0 });
      assert.equal(self.workspace.managerId, target(1)); assert.equal(self.workspace.version, 1);
      assert.equal((await service.get(identities[1], managedOrg.id)).organization.role, 'admin');
      assert.equal((await WorkspaceMembership.collection.findOne({ workspaceId, userId: users[0]._id })).state, 'active');
      await assert.rejects(service.manager(identities[1], managedOrg.id, workspace.id, { managerId: target(4), expectedVersion: 1 }), { code: 'ORGANIZATION_MEMBER_REQUIRED' });
      await assert.rejects(service.manager(identities[1], managedOrg.id, workspace.id, { managerId: target(3), expectedVersion: 1 }), { code: 'ORGANIZATION_MEMBER_REQUIRED' });
      const replaced = await service.manager(identities[1], managedOrg.id, workspace.id, { managerId: target(2), expectedVersion: 1 });
      assert.equal(replaced.workspace.version, 2);
      assert.equal((await WorkspaceMembership.collection.findOne({ workspaceId, userId: users[1]._id })).state, 'active');
      await service.role(identities[0], managedOrg.id, target(1), { role: 'member', expectedVersion: 1 });
      assert.equal((await wsService.get(identities[1], workspace.id)).workspace.role, 'member');
      await assert.rejects(work.createProject(identities[1], workspace.id, { name: 'No longer manager' }), { code: 'OWNER_REQUIRED' });
      assert.equal((await wsService.get(identities[2], workspace.id)).workspace.role, 'manager');
      await assert.rejects(service.manager(identities[2], managedOrg.id, workspace.id, { managerId: target(1), expectedVersion: 2 }), { code: 'ORGANIZATION_ADMIN_REQUIRED' });
      await assert.rejects(service.addMember(identities[2], managedOrg.id, workspace.id, { userId: target(4), expectedVersion: 2 }), { code: 'ORGANIZATION_MEMBER_REQUIRED' });
      assert.equal((await service.addMember(identities[2], managedOrg.id, workspace.id, { userId: target(0), expectedVersion: 2 })).code, 'ALREADY_MEMBER');
      assert.equal(await OrganizationAudit.collection.countDocuments({ organizationId: orgId }), 6);
      const note = await Notification.collection.findOne({ workspaceId, recipientId: users[2]._id, category: 'membership' });
      assert.ok(note);
      assert.equal((await inbox.get(identities[2], String(note._id))).notification.target.type, 'workspace');
      const notes = await inbox.list(identities[2], { category: 'membership', read: 'unread' });
      assert.ok(notes.cutoff);
      await inbox.readAll(identities[2], { cutoff: notes.cutoff });
      assert.equal((await inbox.list(identities[2], { category: 'membership', read: 'unread' })).unreadCount, 0);
      await assert.rejects(service.audit(identities[2], managedOrg.id, {}), { code: 'ORGANIZATION_ADMIN_REQUIRED' });
      assert.equal((await service.audit(identities[0], managedOrg.id, { limit: '2' })).items.length, 2);
      // Reassigning an inactive Workspace member resets overrides, preserves a single pair and emits once.
      await WorkspaceMembership.collection.updateOne({ workspaceId, userId: users[1]._id }, { $set: { state: 'inactive', leftAt: new Date(), exitReason: 'left' } });
      const added = await service.addMember(identities[2], managedOrg.id, workspace.id, { userId: target(1), expectedVersion: 2 });
      assert.equal(added.workspaceVersion, 3); assert.equal(added.code, 'WORKSPACE_MEMBER_ADDED');
      assert.equal((await service.addMember(identities[2], managedOrg.id, workspace.id, { userId: target(1), expectedVersion: 3 })).code, 'ALREADY_MEMBER');
      assert.equal(await Notification.collection.countDocuments({ workspaceId, recipientId: users[1]._id, category: 'membership' }), 1);
      assert.equal(await WorkspaceMembership.collection.countDocuments({ workspaceId, userId: users[1]._id }), 1);
      await assert.rejects(service.manager(identities[0], second.id, workspace.id, { managerId: target(1), expectedVersion: 3 }), { code: 'ORGANIZATION_UNAVAILABLE' });
      const headers = { authorization: 'Bearer fixture', origin: 'http://localhost:5173', 'content-type': 'application/json' };
      const base = `http://127.0.0.1:${server.address().port}/organizations/${managedOrg.id}`;
      assert.equal((await fetch(`${base}/members`, { headers })).status, 200);
      assert.equal((await fetch(`${base}/audit`, { headers })).status, 200);
      assert.equal((await fetch(`${base}/members/${target(2)}/role`, { method: 'PATCH', headers, body: JSON.stringify({ role: 'owner', expectedVersion: 0 }) })).status, 400);
      const race = await Promise.allSettled([1, 2].map(() => service.role(identities[0], managedOrg.id, target(2), { role: 'admin', expectedVersion: 0 })));
      assert.equal(race.filter(x => x.status === 'fulfilled').length, 1);
      assert.equal(race.find(x => x.status === 'rejected').reason.code, 'VERSION_CONFLICT');
      const afterRole = await OrganizationMembership.collection.findOne({ organizationId: orgId, userId: users[2]._id });
      assert.ok(['admin', 'member'].includes(afterRole.role));
      const transferRace = await Promise.allSettled([1, 2].map(index => service.transfer(identities[0], managedOrg.id, { memberId: target(index), expectedVersion: 0 })));
      assert.equal(transferRace.filter(x => x.status === 'fulfilled').length, 1);
      const orgRecord = await Organization.collection.findOne({ _id: orgId });
      assert.equal(orgRecord.version, 1);
      assert.equal((await service.get(identities[0], managedOrg.id)).organization.role, 'member');
      await assert.rejects(service.role(identities[0], managedOrg.id, target(1), { role: 'admin', expectedVersion: 2 }), { code: 'ORGANIZATION_OWNER_REQUIRED' });
      assert.equal(await OrganizationAudit.collection.countDocuments({ organizationId: orgId, action: 'ownership_transferred' }), 1);
      // Earlier test deliberately left an inactive Manager to exercise fail-closed access.
      const initial = await auditOrganizationScope(mongoose.connection.db);
      assert.equal(initial.issues.missingManagerMembership, 1);
      await Workspace.collection.updateOne({ _id: workspaceIds[0] }, { $set: { managerId: users[0]._id } });
      const valid = await auditOrganizationScope(mongoose.connection.db);
      assert.equal(valid.valid, true);
      assert.ok(valid.legacyMissingFields > 0);
    });
    await t.test('revoked session denies reads even with previously issued claims', async () => {
      await Session.collection.updateOne({ _id: sessions[0]._id }, { $set: { revokedAt: new Date() } });
      await assert.rejects(service.get(identities[0], first.id), { code: 'UNAUTHENTICATED' });
    });
  } finally {
    if (server) await new Promise(resolve => server.close(resolve));
    for (const model of [EmailOutbox, Notification, TaskComment, Task, Project, WorkspaceMembership]) await model.collection.deleteMany({ workspaceId: { $in: workspaceIds } });
    await Workspace.collection.deleteMany({ _id: { $in: workspaceIds } });
    await OrganizationMembership.collection.deleteMany({ organizationId: { $in: organizations } });
    await OrganizationAudit.collection.deleteMany({ organizationId: { $in: organizations } });
    await Organization.collection.deleteMany({ _id: { $in: organizations } });
    await Session.collection.deleteMany({ _id: { $in: sessions.map(x => x._id) } });
    await User.collection.deleteMany({ _id: { $in: users.map(x => x._id) } });
    await mongoose.disconnect();
  }
});
