import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { once } from 'node:events';
import mongoose from 'mongoose';
import { connectDatabase } from '../src/database.js';
import { models, User, Session, Organization, OrganizationMembership, OrganizationInvitation, OrganizationAudit, Workspace, WorkspaceMembership, Project, Task, TaskComment, Notification, EmailOutbox } from '../src/models/index.js';
import { createOrganizationService } from '../src/organizations/service.js';
import { createMongoOrganizationStore } from '../src/organizations/mongo-store.js';
import { createWorkspaceService } from '../src/workspaces/service.js';
import { createMongoWorkspaceStore } from '../src/workspaces/mongo-store.js';
import { createWorkService } from '../src/work/service.js';
import { createMongoWorkStore } from '../src/work/mongo-store.js';
import { createNotificationsService } from '../src/notifications/service.js';
import { createMongoNotificationsStore } from '../src/notifications/mongo-store.js';
import { cutoffCodec } from '../src/notifications/input.js';
import { dispatchInvitationMail } from '../src/mail/invitation-mail.js';
import { createDeliveryCrypto } from '../src/auth/delivery-crypto.js';
import { tokenHash } from '../src/auth/tokens.js';
import { mailContent } from '../src/mail/provider.js';
import { createApp } from '../src/app.js';
import { testConfig } from '../test-support/auth-store.js';

test('Organization invitation/admission/exit lifecycle on isolated MongoDB', { skip: !process.env.TEST_MONGODB_URI, timeout: 90_000 }, async t => {
  assert.equal(new URL(process.env.TEST_MONGODB_URI).pathname.slice(1), 'workflow_auth_test');
  await connectDatabase(process.env.TEST_MONGODB_URI);
  const config = testConfig(), users = [], sessions = [], auths = [], orgIds = [], workspaceIds = [];
  const service = createOrganizationService({ store: createMongoOrganizationStore({ config }) });
  const workspaceService = createWorkspaceService({ store: createMongoWorkspaceStore({ config }) });
  const work = createWorkService({ store: createMongoWorkStore() });
  const cutoff = cutoffCodec(config.accessKeyHex);
  const inbox = createNotificationsService({ store: createMongoNotificationsStore({ cutoff }), cutoff });
  const crypto = createDeliveryCrypto(config.mailKeyHex);
  const userId = index => String(users[index]._id);
  const membership = (org, index) => OrganizationMembership.collection.findOne({ organizationId: new mongoose.Types.ObjectId(org.id), userId: users[index]._id });
  let server;
  try {
    for (const model of Object.values(models)) await model.createIndexes();
    for (let i = 0; i < 6; i++) {
      const user = new User({ displayName: `Lifecycle ${i}`, email: `${randomUUID()}@example.com`, emailVerifiedAt: i === 3 ? null : new Date(), termsAcceptance: { version: 'test', acceptedAt: new Date() } });
      await user.save(); users.push(user);
      const session = new Session({ userId: user._id, refreshTokenHash: String(i + 1).repeat(64), authVersionAtIssue: 0, expiresAt: new Date(Date.now() + 120_000), lastSeenAt: new Date() });
      await session.save(); sessions.push(session); auths.push({ claims: { sub: userId(i), sid: String(session._id), av: 0 } });
    }
    const org = (await service.create(auths[0], { name: 'Lifecycle Org' })).organization; orgIds.push(new mongoose.Types.ObjectId(org.id));
    const other = (await service.create(auths[2], { name: 'Other Org' })).organization; orgIds.push(new mongoose.Types.ObjectId(other.id));
    const first = (await service.createWorkspace(auths[0], org.id, { name: 'Design' })).workspace;
    const second = (await service.createWorkspace(auths[0], org.id, { name: 'Engineering' })).workspace;
    const foreign = (await service.createWorkspace(auths[2], other.id, { name: 'Foreign' })).workspace;
    workspaceIds.push(...[first, second, foreign].map(w => new mongoose.Types.ObjectId(w.id)));
    const invite = async (index, workspaceId = null) => service.invite(auths[0], org.id, { email: users[index].email, ...(workspaceId ? { workspaceId } : {}) });
    const rawToken = async invitationId => {
      const job = await EmailOutbox.collection.findOne({ organizationInvitationId: new mongoose.Types.ObjectId(invitationId) });
      return crypto.open(job.encryptedDeliveryData, job.eventId).token;
    };
    let initialInvite;
    await t.test('email-only Member invitation, public preview, encrypted outbox and in-app recipient scope', async () => {
      await assert.rejects(service.invite(auths[2], org.id, { email: users[1].email }), { code: 'ORGANIZATION_UNAVAILABLE' });
      await assert.rejects(service.invite(auths[0], org.id, { email: users[1].email, workspaceId: foreign.id }), { code: 'WORKSPACE_UNAVAILABLE' });
      assert.throws(() => service.invite(auths[0], org.id, { email: users[1].email, role: 'admin' }));
      initialInvite = await invite(1, first.id);
      const filteredInvites = await service.invitations(auths[0], org.id, { q: users[1].email, state: 'active', limit: '1' });
      assert.equal(filteredInvites.total, 1);
      assert.equal(filteredInvites.items[0].id, initialInvite.invitation.id);
      assert.equal((await service.invitations(auths[0], org.id, { state: 'revoked' })).total, 0);
      assert.throws(() => service.invitations(auths[0], org.id, { organizationId: 'f'.repeat(24) }), /INVALID_INPUT/);
      assert.equal(initialInvite.invitation.role, 'member'); assert.equal(await membership(org, 1), null);
      const raw = await rawToken(initialInvite.invitation.id);
      const doc = await OrganizationInvitation.collection.findOne({ _id: new mongoose.Types.ObjectId(initialInvite.invitation.id) });
      assert.equal(doc.tokenHash, tokenHash(raw)); assert.ok(!JSON.stringify(initialInvite).includes(raw));
      const preview = await service.previewInvitation({ token: raw });
      assert.equal(preview.preview.organizationName, org.name); assert.equal(preview.preview.workspaceName, first.name);
      assert.ok(!JSON.stringify(preview).includes(users[1].email));
      const notes = await inbox.list(auths[1], { category: 'organization_invitation' });
      assert.equal(notes.items.length, 1); assert.equal(notes.items[0].target.type, 'organization_invitation');
      assert.equal((await inbox.list(auths[2], { category: 'organization_invitation' })).items.length, 0);
      await assert.rejects(service.acceptInvitation(auths[2], { token: raw }), { code: 'INVITATION_EMAIL_MISMATCH' });
      let delivery;
      assert.equal((await dispatchInvitationMail({ config, send: async mail => { delivery = mail; return 'capture-org'; } })).state, 'sent');
      assert.equal(delivery.purpose, 'organization_invitation'); assert.equal(delivery.to, users[1].emailCanonical);
      assert.ok(mailContent(delivery).text.includes(first.name));
    });
    await t.test('concurrent accept-by-ID creates single membership and optional Workspace atomically', async () => {
      const results = await Promise.all([1, 2].map(() => service.acceptInvitationById(auths[1], initialInvite.invitation.id, {})));
      assert.ok(results.some(result => result.code === 'ORGANIZATION_JOINED'));
      assert.ok(results.some(result => result.code === 'ALREADY_ACCEPTED'));
      assert.equal((await membership(org, 1)).role, 'member');
      assert.equal(await WorkspaceMembership.collection.countDocuments({ workspaceId: workspaceIds[0], userId: users[1]._id }), 1);
      await assert.rejects(workspaceService.get(auths[1], second.id), { code: 'WORKSPACE_UNAVAILABLE' });
      assert.equal((await inbox.list(auths[1], { category: 'organization_invitation' })).items[0].available, false);
      const privileged = await service.role(auths[0], org.id, userId(1), { role: 'admin', expectedVersion: 0 });
      const additional = await invite(1, second.id);
      await service.acceptInvitationById(auths[1], additional.invitation.id, {});
      assert.equal((await membership(org, 1)).role, 'admin');
      await service.role(auths[0], org.id, userId(1), { role: 'member', expectedVersion: privileged.version });
    });
    await t.test('unverified, revoked, expired and stale invitations cannot grant access', async () => {
      const unverified = await invite(3);
      await assert.rejects(service.acceptInvitationById(auths[3], unverified.invitation.id, {}), { code: 'EMAIL_VERIFICATION_REQUIRED' });
      const revoked = await invite(4);
      await assert.rejects(service.revokeInvitation(auths[0], org.id, revoked.invitation.id, { expectedVersion: 9 }), { code: 'VERSION_CONFLICT' });
      const raw = await rawToken(revoked.invitation.id);
      await service.revokeInvitation(auths[0], org.id, revoked.invitation.id, { expectedVersion: 0 });
      await assert.rejects(service.acceptInvitation(auths[4], { token: raw }), { code: 'INVITATION_UNAVAILABLE' });
      const expired = await invite(5);
      await OrganizationInvitation.collection.updateOne({ _id: new mongoose.Types.ObjectId(expired.invitation.id) }, { $set: { expiresAt: new Date(Date.now() - 1) } });
      await assert.rejects(service.acceptInvitationById(auths[5], expired.invitation.id, {}), { code: 'INVITATION_UNAVAILABLE' });
      assert.equal(await membership(org, 4), null); assert.equal(await membership(org, 5), null);
      await service.revokeInvitation(auths[0], org.id, unverified.invitation.id, { expectedVersion: 0 });
      let calls = 0;
      assert.equal((await dispatchInvitationMail({ config, send: async () => { calls++; return 'unexpected'; } })).state, 'cancelled');
      assert.equal(calls, 0);
    });
    await t.test('Organization mail retries are redacted and parallel dispatch holds a single lease', async () => {
      const retry = await invite(5);
      assert.equal((await dispatchInvitationMail({ config, send: async () => { throw new Error('secret recipient/token text'); } })).state, 'retry_or_failed');
      const query = { organizationInvitationId: new mongoose.Types.ObjectId(retry.invitation.id) };
      const failed = await EmailOutbox.collection.findOne(query);
      assert.equal(failed.lastErrorCode, 'INVITATION_MAIL_DELIVERY_FAILED');
      assert.equal(failed.state, 'pending');
      await EmailOutbox.collection.updateOne(query, { $set: { nextAttemptAt: new Date(Date.now() - 1) } });
      let deliveries = 0;
      const results = await Promise.all([1, 2].map(() => dispatchInvitationMail({ config, send: async () => { deliveries++; return 'capture-retry'; } })));
      assert.equal(deliveries, 1); assert.ok(results.some(result => result.state === 'sent'));
      assert.equal((await EmailOutbox.collection.findOne(query)).encryptedDeliveryData, null);
    });
    await t.test('leave cascades Workspace rights, assignees and queued work email but preserves history and standalone', async () => {
      const independent = (await workspaceService.create(auths[1], { name: 'Independent' })).workspace; workspaceIds.push(new mongoose.Types.ObjectId(independent.id));
      const project = (await work.createProject(auths[0], first.id, { name: 'Project' })).project;
      const archived = (await work.createProject(auths[0], second.id, { name: 'Archived Project' })).project;
      const open = (await work.createTask(auths[1], project.id, { title: 'Open', assigneeId: userId(1) })).task;
      const completed = (await work.createTask(auths[0], project.id, { title: 'Done', assigneeId: userId(1) })).task;
      await work.status(auths[1], completed.id, { status: 'done', expectedVersion: 0 });
      const archivedTask = (await work.createTask(auths[0], archived.id, { title: 'Archived unfinished', assigneeId: userId(1) })).task;
      await work.state(auths[0], archived.id, { state: 'archived', expectedVersion: 0 });
      const content = { format: 'prosemirror-json', schemaVersion: 1, document: { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Keep my comment' }] }] } };
      const comment = (await work.createComment(auths[1], open.id, { content })).comment;
      const current = await membership(org, 1);
      await assert.rejects(service.leave(auths[0], org.id, { expectedVersion: 0 }), { code: 'TRANSFER_REQUIRED' });
      await assert.rejects(service.leave(auths[1], org.id, { expectedVersion: current.version + 1 }), { code: 'VERSION_CONFLICT' });
      await service.leave(auths[1], org.id, { expectedVersion: current.version });
      assert.equal((await membership(org, 1)).state, 'inactive');
      assert.equal(await WorkspaceMembership.collection.countDocuments({ workspaceId: { $in: workspaceIds.slice(0, 2) }, userId: users[1]._id, state: 'active' }), 0);
      for (const taskId of [open.id, archivedTask.id]) assert.equal((await Task.collection.findOne({ _id: new mongoose.Types.ObjectId(taskId) })).assigneeId, null);
      const done = await work.getTask(auths[0], completed.id); assert.equal(done.task.assigneeId, userId(1)); assert.equal(done.task.assigneeLeft, true);
      assert.equal((await Task.collection.findOne({ _id: new mongoose.Types.ObjectId(open.id) })).createdBy.toString(), userId(1));
      assert.ok(await TaskComment.collection.findOne({ _id: new mongoose.Types.ObjectId(comment.id) }));
      assert.equal(await EmailOutbox.collection.countDocuments({ category: 'work', userId: users[1]._id, workspaceId: { $in: workspaceIds.slice(0, 2) }, state: { $in: ['pending', 'processing'] } }), 0);
      assert.equal((await workspaceService.get(auths[1], independent.id)).workspace.role, 'owner');
      await assert.rejects(work.getTask(auths[1], open.id), { code: 'RESOURCE_UNAVAILABLE' });
      const rejoin = await invite(1, first.id);
      await service.acceptInvitationById(auths[1], rejoin.invitation.id, {});
      assert.equal((await membership(org, 1)).role, 'member');
      assert.equal((await Task.collection.findOne({ _id: new mongoose.Types.ObjectId(open.id) })).assigneeId, null);
      assert.equal((await work.getTask(auths[0], completed.id)).task.assigneeLeft, false);
    });
    await t.test('owner/admin protection, Manager handoff and accept/revoke race remain consistent', async () => {
      const joins = await invite(4);
      await service.acceptInvitationById(auths[4], joins.invitation.id, {});
      await service.role(auths[0], org.id, userId(4), { role: 'admin', expectedVersion: 0 });
      await assert.rejects(service.remove(auths[4], org.id, userId(0), { expectedVersion: 0 }), { code: 'CANNOT_REMOVE_OWNER' });
      const version = (await membership(org, 1)).version;
      await service.role(auths[0], org.id, userId(1), { role: 'admin', expectedVersion: version });
      await assert.rejects(service.remove(auths[4], org.id, userId(1), { expectedVersion: version + 1 }), { code: 'ORGANIZATION_OWNER_REQUIRED' });
      await service.role(auths[0], org.id, userId(1), { role: 'member', expectedVersion: version + 1 });
      const workspace = await Workspace.collection.findOne({ _id: workspaceIds[0] });
      await service.manager(auths[0], org.id, first.id, { managerId: userId(1), expectedVersion: workspace.version });
      await assert.rejects(service.remove(auths[0], org.id, userId(1), { expectedVersion: (await membership(org, 1)).version }), { code: 'MANAGER_REPLACEMENT_REQUIRED' });
      const changed = await Workspace.collection.findOne({ _id: workspaceIds[0] });
      await service.manager(auths[0], org.id, first.id, { managerId: userId(0), expectedVersion: changed.version });
      await service.remove(auths[0], org.id, userId(1), { expectedVersion: (await membership(org, 1)).version });
      assert.equal((await membership(org, 1)).state, 'inactive');
      const race = await invite(2);
      await Promise.allSettled([service.acceptInvitationById(auths[2], race.invitation.id, {}), service.revokeInvitation(auths[0], org.id, race.invitation.id, { expectedVersion: 0 })]);
      const value = await OrganizationInvitation.collection.findOne({ _id: new mongoose.Types.ObjectId(race.invitation.id) });
      assert.notEqual(Boolean(value.acceptedAt), Boolean(value.revokedAt));
      assert.equal(Boolean((await membership(org, 2))?.state === 'active'), Boolean(value.acceptedAt));
    });
    await t.test('remove versus Task edit rechecks Org role at commit and clears assignments', async () => {
      const ws = await Workspace.collection.findOne({ _id: workspaceIds[0] });
      await service.addMember(auths[0], org.id, first.id, { userId: userId(4), expectedVersion: ws.version });
      const project = (await work.createProject(auths[0], first.id, { name: 'Race project' })).project;
      const task = (await work.createTask(auths[0], project.id, { title: 'Race Task', assigneeId: userId(4) })).task;
      const version = (await membership(org, 4)).version;
      const results = await Promise.allSettled([
        work.updateTask(auths[4], task.id, { title: 'Edited before removal', expectedVersion: 0 }),
        service.remove(auths[0], org.id, userId(4), { expectedVersion: version }),
      ]);
      assert.equal(results[1].status, 'fulfilled');
      assert.equal((await membership(org, 4)).state, 'inactive');
      const stored = await Task.collection.findOne({ _id: new mongoose.Types.ObjectId(task.id) });
      assert.equal(stored.assigneeId, null);
      await assert.rejects(work.updateTask(auths[4], task.id, { title: 'After removal', expectedVersion: stored.version }), { code: 'RESOURCE_UNAVAILABLE' });
    });
    await t.test('HTTP origin/auth/DTO and recipient-bound accept-by-ID', async () => {
      const authService = { authenticate: async () => auths[0] };
      const app = createApp({ authService, authConfig: config, organizationService: service });
      server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
      const base = `http://127.0.0.1:${server.address().port}`;
      const headers = { authorization: 'Bearer fixture', origin: config.webOrigin, 'content-type': 'application/json' };
      assert.equal((await fetch(`${base}/organizations/${org.id}/invitations`, { headers })).status, 200);
      assert.equal((await fetch(`${base}/organization-invitations/accept`, { method: 'POST', headers: { origin: config.webOrigin, 'content-type': 'application/json' }, body: '{"token":"invalid"}' })).status, 401);
      const pending = await invite(5);
      const raw = await rawToken(pending.invitation.id);
      assert.equal((await fetch(`${base}/organization-invitations/preview`, { method: 'POST', headers, body: JSON.stringify({ token: raw }) })).status, 200);
      assert.equal((await fetch(`${base}/organization-invitations/preview`, { method: 'POST', headers: { ...headers, origin: 'http://evil.example' }, body: JSON.stringify({ token: raw }) })).status, 403);
      assert.equal((await fetch(`${base}/organization-invitations/${pending.invitation.id}/accept`, { method: 'POST', headers, body: '{}' })).status, 404);
      assert.equal((await fetch(`${base}/organizations/${org.id}/invitations`, { method: 'POST', headers, body: JSON.stringify({ email: users[5].email, role: 'admin' }) })).status, 400);
    });
  } finally {
    if (server) await new Promise(resolve => server.close(resolve));
    for (const model of [EmailOutbox, Notification]) await model.collection.deleteMany({ $or: [{ organizationId: { $in: orgIds } }, { workspaceId: { $in: workspaceIds } }] });
    for (const model of [TaskComment, Task, Project, WorkspaceMembership]) await model.collection.deleteMany({ workspaceId: { $in: workspaceIds } });
    await Workspace.collection.deleteMany({ _id: { $in: workspaceIds } });
    for (const model of [OrganizationMembership, OrganizationInvitation, OrganizationAudit]) await model.collection.deleteMany({ organizationId: { $in: orgIds } });
    await Organization.collection.deleteMany({ _id: { $in: orgIds } });
    await Session.collection.deleteMany({ _id: { $in: sessions.map(x => x._id) } });
    await User.collection.deleteMany({ _id: { $in: users.map(x => x._id) } });
    await mongoose.disconnect();
  }
});
