import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { once } from 'node:events';
import mongoose from 'mongoose';
import { connectDatabase } from '../src/database.js';
import { models, User, Session, Workspace, WorkspaceMembership, Project, Task, TaskComment, ProjectGuest, ProjectGuestInvitation, ProjectAccessAudit, Organization, OrganizationMembership, OrganizationInvitation, OrganizationAudit, EmailOutbox, Notification } from '../src/models/index.js';
import { createWorkspaceService } from '../src/workspaces/service.js';
import { createMongoWorkspaceStore } from '../src/workspaces/mongo-store.js';
import { createWorkService } from '../src/work/service.js';
import { createMongoWorkStore } from '../src/work/mongo-store.js';
import { createOrganizationService } from '../src/organizations/service.js';
import { createMongoOrganizationStore } from '../src/organizations/mongo-store.js';
import { createNotificationsService } from '../src/notifications/service.js';
import { createMongoNotificationsStore } from '../src/notifications/mongo-store.js';
import { cutoffCodec } from '../src/notifications/input.js';
import { dispatchInvitationMail } from '../src/mail/invitation-mail.js';
import { createApp } from '../src/app.js';
import { testConfig } from '../test-support/auth-store.js';

test('Project Lead and Guest scoped access on isolated MongoDB', { skip: !process.env.TEST_MONGODB_URI, timeout: 90_000 }, async t => {
  assert.equal(new URL(process.env.TEST_MONGODB_URI).pathname.slice(1), 'workflow_auth_test');
  await connectDatabase(process.env.TEST_MONGODB_URI);
  const config = testConfig(), users = [], sessions = [], auths = [], workspaceIds = [], orgIds = [];
  const ws = createWorkspaceService({ store: createMongoWorkspaceStore({ config }) });
  const work = createWorkService({ store: createMongoWorkStore({ config }) });
  const orgs = createOrganizationService({ store: createMongoOrganizationStore({ config }) });
  const cutoff = cutoffCodec(config.accessKeyHex);
  const inbox = createNotificationsService({ store: createMongoNotificationsStore({ cutoff }), cutoff });
  const uid = index => String(users[index]._id);
  const content = text => ({ format: 'prosemirror-json', schemaVersion: 1, document: { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text }] }] } });
  const token = result => new URLSearchParams(new URL(result.url).hash.slice(1)).get('token');
  let server, emailInvite, link, task, comment;
  try {
    for (const model of Object.values(models)) await model.createIndexes();
    for (let i = 0; i < 7; i++) {
      const user = new User({ displayName: `Access ${i}`, email: `${randomUUID()}@example.com`, emailVerifiedAt: i === 5 ? null : new Date(), termsAcceptance: { version: 'test', acceptedAt: new Date() } });
      await user.save(); users.push(user);
      const session = new Session({ userId: user._id, refreshTokenHash: String(i + 1).repeat(64), authVersionAtIssue: 0, expiresAt: new Date(Date.now() + 120_000), lastSeenAt: new Date() });
      await session.save(); sessions.push(session); auths.push({ claims: { sub: uid(i), sid: String(session._id), av: 0 } });
    }
    const workspace = (await ws.create(auths[0], { name: 'Access Workspace' })).workspace; workspaceIds.push(new mongoose.Types.ObjectId(workspace.id));
    const memberLink = await ws.invite(auths[0], workspace.id, { type: 'LINK' });
    for (const i of [1, 2, 4]) await ws.accept(auths[i], { token: token(memberLink) });
    const a = (await work.createProject(auths[0], workspace.id, { name: 'Shared A' })).project;
    const b = (await work.createProject(auths[0], workspace.id, { name: 'Private B' })).project;
    task = (await work.createTask(auths[2], a.id, { title: 'Task A', assigneeId: uid(2) })).task;
    const privateTask = (await work.createTask(auths[0], b.id, { title: 'Task B', assigneeId: uid(2) })).task;
    await t.test('Lead requires current Workspace membership and cannot manage other Projects or Workspace', async () => {
      const lead = await work.lead(auths[0], a.id, { leadId: uid(1), expectedVersion: 0 }); assert.equal(lead.project.leadId, uid(1));
      await assert.rejects(work.lead(auths[1], b.id, { leadId: uid(1), expectedVersion: 0 }), { code: 'OWNER_REQUIRED' });
      await assert.rejects(work.lead(auths[0], b.id, { leadId: uid(3), expectedVersion: 0 }), { code: 'ASSIGNEE_NOT_MEMBER' });
      assert.equal((await work.getProject(auths[1], a.id)).project.accessRole, 'lead');
      task = (await work.updateTask(auths[1], task.id, { title: 'Lead edited', expectedVersion: 0 })).task;
      await work.updateProject(auths[1], a.id, { description: content('Project goal'), expectedVersion: 1 });
      await assert.rejects(work.updateProject(auths[1], a.id, { name: 'Unauthorized rename', expectedVersion: 2 }), { code: 'OWNER_REQUIRED' });
      await assert.rejects(work.updateTask(auths[1], privateTask.id, { title: 'Other project', expectedVersion: 0 }), { code: 'TASK_EDIT_FORBIDDEN' });
      await assert.rejects(work.inviteGuest(auths[1], a.id, { type: 'LINK' }), { code: 'OWNER_REQUIRED' });
    });
    await t.test('Guest EMAIL/LINK acceptance never creates Org/Workspace membership; reads only shared Project', async () => {
      emailInvite = await work.inviteGuest(auths[0], a.id, { type: 'EMAIL', email: users[3].email });
      assert.equal(emailInvite.invitation.role, 'guest');
      const notes = await inbox.list(auths[3], { category: 'project_invitation' }); assert.equal(notes.items[0].target.type, 'project_invitation');
      let mail;
      assert.equal((await dispatchInvitationMail({ config, send: async value => { mail = value; return 'capture-guest'; } })).state, 'sent');
      assert.equal(mail.purpose, 'project_guest_invitation');
      const raw = new URLSearchParams(new URL(mail.url).hash.slice(1)).get('token');
      const preview = await work.previewGuestInvitation({ token: raw }); assert.equal(preview.preview.projectName, a.name); assert.equal(preview.preview.role, 'guest');
      assert.ok(!JSON.stringify(preview).includes(users[3].email));
      await assert.rejects(work.acceptGuestInvitation(auths[2], { token: raw }), { code: 'INVITATION_EMAIL_MISMATCH' });
      const accepted = await Promise.all([1, 2].map(() => work.acceptGuestInvitationById(auths[3], emailInvite.invitation.id, {})));
      assert.ok(accepted.some(result => result.code === 'PROJECT_GUEST_JOINED')); assert.ok(accepted.some(result => result.code === 'ALREADY_GUEST'));
      assert.equal(await WorkspaceMembership.collection.countDocuments({ userId: users[3]._id }), 0);
      assert.equal(await OrganizationMembership.collection.countDocuments({ userId: users[3]._id }), 0);
      assert.equal((await work.getProject(auths[3], a.id)).project.accessRole, 'guest');
      assert.equal((await work.tasks(auths[3], a.id, {})).total, 1);
      assert.equal((await work.board(auths[3], a.id, {})).columns.todo.total, 1);
      assert.equal((await work.shared(auths[3], {})).items.length, 1);
      assert.equal((await work.mine(auths[3], {})).total, 0);
      await assert.rejects(work.getProject(auths[3], b.id), { code: 'RESOURCE_UNAVAILABLE' });
      await assert.rejects(work.getTask(auths[3], privateTask.id), { code: 'RESOURCE_UNAVAILABLE' });
      await assert.rejects(ws.get(auths[3], workspace.id), { code: 'WORKSPACE_UNAVAILABLE' });
      await assert.rejects(ws.members(auths[3], workspace.id, {}), { code: 'WORKSPACE_UNAVAILABLE' });
      await assert.rejects(work.projects(auths[3], workspace.id, {}), { code: 'RESOURCE_UNAVAILABLE' });
      const dto = (await work.getTask(auths[3], task.id)).task;
      assert.deepEqual(dto.permissions, { edit: false, delete: false, status: false, requestReopen: false, manageReopen: false, checklistStructure: false, checklistTick: false });
      assert.ok(!JSON.stringify(dto).includes('@example.com'));
      assert.equal((await inbox.list(auths[3], { category: 'project_invitation' })).items[0].available, false);
      link = await work.inviteGuest(auths[0], a.id, { type: 'LINK' });
      await assert.rejects(work.acceptGuestInvitation(auths[5], { token: token(link) }), { code: 'EMAIL_VERIFICATION_REQUIRED' });
    });
    await t.test('Guest writes only own Comments; cannot assign, create, edit, delete or change Task status', async () => {
      await assert.rejects(work.createTask(auths[3], a.id, { title: 'Guest task' }), { code: 'TASK_CREATE_FORBIDDEN' });
      await assert.rejects(work.updateTask(auths[3], task.id, { title: 'Guest edit', expectedVersion: task.version }), { code: 'TASK_EDIT_FORBIDDEN' });
      await assert.rejects(work.status(auths[3], task.id, { status: 'done', expectedVersion: task.version }), { code: 'TASK_STATUS_FORBIDDEN' });
      await assert.rejects(work.deleteTask(auths[3], task.id, { expectedVersion: task.version }), { code: 'TASK_EDIT_FORBIDDEN' });
      await assert.rejects(work.checklist(auths[3], task.id, { expectedVersion: task.version, items: [] }), { code: 'TASK_EDIT_FORBIDDEN' });
      await assert.rejects(work.tickChecklist(auths[3], task.id, '00000000-0000-0000-0000-000000000000', { expectedVersion: task.version, checked: true }), { code: 'TASK_STATUS_FORBIDDEN' });
      await assert.rejects(work.createLabel(auths[3], a.id, { name: 'Guest label' }), { code: 'PROJECT_MANAGEMENT_REQUIRED' });
      assert.ok((await work.activity(auths[3], task.id, {})).items.length);
      await assert.rejects(work.updateTask(auths[0], task.id, { assigneeId: uid(3), expectedVersion: task.version }), { code: 'ASSIGNEE_NOT_MEMBER' });
      comment = (await work.createComment(auths[3], task.id, { content: content('Guest feedback') })).comment;
      comment = (await work.updateComment(auths[3], task.id, comment.id, { content: content('Edited feedback'), expectedVersion: 0 })).comment;
      await assert.rejects(work.updateComment(auths[1], task.id, comment.id, { content: content('Lead overwrote'), expectedVersion: 1 }), { code: 'COMMENT_AUTHOR_REQUIRED' });
      await assert.rejects(work.guests(auths[3], a.id, {}), { code: 'WORKSPACE_UNAVAILABLE' });
    });
    await t.test('expired/revoked invitations and cross-Project IDs cannot grant Guest access', async () => {
      const expired = await work.inviteGuest(auths[0], a.id, { type: 'LINK' });
      await ProjectGuestInvitation.collection.updateOne({ _id: new mongoose.Types.ObjectId(expired.invitation.id) }, { $set: { expiresAt: new Date(Date.now() - 1) } });
      await assert.rejects(work.acceptGuestInvitation(auths[6], { token: token(expired) }), { code: 'INVITATION_UNAVAILABLE' });
      await assert.rejects(work.previewGuestInvitation({ token: token(expired) }), { code: 'INVITATION_UNAVAILABLE' });
      const email = await work.inviteGuest(auths[0], a.id, { type: 'EMAIL', email: users[6].email });
      await assert.rejects(work.revokeGuestInvitation(auths[0], b.id, email.invitation.id, { expectedVersion: 0 }), { code: 'INVITATION_UNAVAILABLE' });
      await work.revokeGuestInvitation(auths[0], a.id, email.invitation.id, { expectedVersion: 0 });
      await assert.rejects(work.acceptGuestInvitationById(auths[6], email.invitation.id, {}), { code: 'INVITATION_UNAVAILABLE' });
      assert.equal(await ProjectGuest.collection.countDocuments({ userId: users[6]._id }), 0);
    });
    await t.test('former Creator/Assignee returning as Guest has no inherited Task write permission', async () => {
      let old = (await work.createTask(auths[4], a.id, { title: 'Historical task', assigneeId: uid(4) })).task;
      old = (await work.updateTask(auths[0], old.id, { title: 'Owner updated', expectedVersion: old.version })).task;
      old = (await work.status(auths[4], old.id, { status: 'done', expectedVersion: old.version })).task;
      const note = await Notification.collection.findOne({ recipientId: users[4]._id, taskId: new mongoose.Types.ObjectId(old.id), category: 'work' }); assert.ok(note);
      const current = await WorkspaceMembership.collection.findOne({ workspaceId: workspaceIds[0], userId: users[4]._id });
      await ws.leave(auths[4], workspace.id, { expectedVersion: current.version });
      assert.equal((await inbox.get(auths[4], String(note._id))).notification.available, false);
      await work.acceptGuestInvitation(auths[4], { token: token(link) });
      assert.equal((await work.getTask(auths[4], old.id)).task.assigneeId, uid(4));
      assert.deepEqual((await work.getTask(auths[4], old.id)).task.permissions, { edit: false, delete: false, status: false, requestReopen: false, manageReopen: false, checklistStructure: false, checklistTick: false });
      await assert.rejects(work.status(auths[4], old.id, { status: 'in_progress', expectedVersion: old.version }), { code: 'TASK_STATUS_FORBIDDEN' });
      await assert.rejects(work.updateTask(auths[4], old.id, { title: 'Creator bypass', expectedVersion: old.version }), { code: 'TASK_EDIT_FORBIDDEN' });
      assert.equal((await inbox.get(auths[4], String(note._id))).notification.available, true);
    });
    await t.test('Guest revoke/link revoke and concurrent Lead changes respect CAS and current access', async () => {
      const grant = await ProjectGuest.collection.findOne({ projectId: new mongoose.Types.ObjectId(a.id), userId: users[3]._id });
      const race = await Promise.allSettled([work.createComment(auths[3], task.id, { content: content('Racing feedback') }), work.revokeGuest(auths[0], a.id, uid(3), { expectedVersion: grant.version })]);
      assert.equal(race[1].status, 'fulfilled');
      await assert.rejects(work.getTask(auths[3], task.id), { code: 'RESOURCE_UNAVAILABLE' });
      await assert.rejects(work.updateComment(auths[3], task.id, comment.id, { content: content('After revoke'), expectedVersion: 1 }), { code: 'RESOURCE_UNAVAILABLE' });
      assert.ok(await TaskComment.collection.findOne({ _id: new mongoose.Types.ObjectId(comment.id) }));
      await work.revokeGuestInvitation(auths[0], a.id, link.invitation.id, { expectedVersion: 0 });
      await assert.rejects(work.acceptGuestInvitation(auths[3], { token: token(link) }), { code: 'INVITATION_UNAVAILABLE' });
      assert.equal((await work.getProject(auths[4], a.id)).project.accessRole, 'guest');
      const fresh = await work.inviteGuest(auths[0], a.id, { type: 'LINK' });
      await Promise.all([1, 2].map(() => work.acceptGuestInvitation(auths[3], { token: token(fresh) })));
      assert.equal(await ProjectGuest.collection.countDocuments({ projectId: new mongoose.Types.ObjectId(a.id), userId: users[3]._id }), 1);
      await work.lead(auths[0], a.id, { leadId: null, expectedVersion: 2 });
      await assert.rejects(work.updateTask(auths[1], task.id, { title: 'Former Lead', expectedVersion: task.version }), { code: 'TASK_EDIT_FORBIDDEN' });
      const leads = await Promise.allSettled([1, 2].map(index => work.lead(auths[0], a.id, { leadId: uid(index), expectedVersion: 3 })));
      assert.equal(leads.filter(result => result.status === 'fulfilled').length, 1);
      assert.equal(leads.find(result => result.status === 'rejected').reason.code, 'VERSION_CONFLICT');
    });
    await t.test('Organization exit removes Lead and Guest grants including Archived; external Guest stays isolated', async () => {
      const org = (await orgs.create(auths[0], { name: 'Guest Org' })).organization; orgIds.push(new mongoose.Types.ObjectId(org.id));
      const orgWorkspace = (await orgs.createWorkspace(auths[0], org.id, { name: 'Org Workspace' })).workspace; workspaceIds.push(new mongoose.Types.ObjectId(orgWorkspace.id));
      const invite = await orgs.invite(auths[0], org.id, { email: users[2].email, workspaceId: orgWorkspace.id });
      await orgs.acceptInvitationById(auths[2], invite.invitation.id, {});
      const project = (await work.createProject(auths[0], orgWorkspace.id, { name: 'Client Org Project' })).project;
      const localTask = (await work.createTask(auths[0], project.id, { title: 'Org task' })).task;
      const guestLink = await work.inviteGuest(auths[0], project.id, { type: 'LINK' });
      await work.acceptGuestInvitation(auths[2], { token: token(guestLink) });
      assert.notEqual((await work.getProject(auths[2], project.id)).project.accessRole, 'guest');
      await work.acceptGuestInvitation(auths[3], { token: token(guestLink) });
      await work.lead(auths[0], project.id, { leadId: uid(2), expectedVersion: 0 });
      await work.state(auths[0], project.id, { state: 'archived', expectedVersion: 1 });
      const member = await OrganizationMembership.collection.findOne({ organizationId: orgIds[0], userId: users[2]._id });
      await orgs.leave(auths[2], org.id, { expectedVersion: member.version });
      const stored = await Project.collection.findOne({ _id: new mongoose.Types.ObjectId(project.id) }); assert.equal(stored.leadId, null);
      assert.equal((await ProjectGuest.collection.findOne({ projectId: stored._id, userId: users[2]._id })).state, 'inactive');
      await assert.rejects(work.getProject(auths[2], project.id), { code: 'RESOURCE_UNAVAILABLE' });
      assert.equal((await work.getProject(auths[3], project.id)).project.accessRole, 'guest');
      await assert.rejects(work.createComment(auths[3], localTask.id, { content: content('Archived feedback') }), { code: 'PROJECT_ARCHIVED' });
      assert.ok((await work.getProject(auths[2], a.id)).project);
    });
    await t.test('HTTP Guest scope and forged role/parent fields are rejected', async () => {
      const authService = { authenticate: async () => auths[3], requireVerified: () => {} };
      server = createApp({ authService, authConfig: config, workService: work }).listen(0, '127.0.0.1'); await once(server, 'listening');
      const base = `http://127.0.0.1:${server.address().port}`;
      const headers = { authorization: 'Bearer fixture', origin: config.webOrigin, 'content-type': 'application/json' };
      assert.equal((await fetch(`${base}/shared-projects`, { headers })).status, 200);
      assert.equal((await fetch(`${base}/projects/${a.id}/board`, { headers })).status, 200);
      assert.equal((await fetch(`${base}/projects/${b.id}`, { headers })).status, 404);
      assert.equal((await fetch(`${base}/projects/${a.id}/tasks`, { method: 'POST', headers, body: '{"title":"Denied"}' })).status, 403);
      assert.equal((await fetch(`${base}/projects/${a.id}/guest-invitations`, { method: 'POST', headers, body: JSON.stringify({ type: 'LINK', role: 'member' }) })).status, 400);
      assert.equal((await fetch(`${base}/project-invitations/preview`, { method: 'POST', headers: { ...headers, origin: 'http://evil.example' }, body: JSON.stringify({ token: token(link) }) })).status, 403);
    });
  } finally {
    if (server) await new Promise(resolve => server.close(resolve));
    for (const model of [EmailOutbox, Notification]) await model.collection.deleteMany({ $or: [{ workspaceId: { $in: workspaceIds } }, { organizationId: { $in: orgIds } }] });
    for (const model of [ProjectGuest, ProjectGuestInvitation, ProjectAccessAudit, TaskComment, Task, Project, WorkspaceMembership]) await model.collection.deleteMany({ workspaceId: { $in: workspaceIds } });
    await Workspace.collection.deleteMany({ _id: { $in: workspaceIds } });
    for (const model of [OrganizationMembership, OrganizationInvitation, OrganizationAudit]) await model.collection.deleteMany({ organizationId: { $in: orgIds } });
    await Organization.collection.deleteMany({ _id: { $in: orgIds } });
    await Session.collection.deleteMany({ _id: { $in: sessions.map(session => session._id) } });
    await User.collection.deleteMany({ _id: { $in: users.map(user => user._id) } });
    await mongoose.disconnect();
  }
});
