import { useAuthLocale } from '../auth/AuthLocale.jsx';
import { workspaceText } from '../../lib/workspace-text.js';
import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import FormField from '../../components/FormField.jsx';
import useDialogFocus from '../../components/useDialogFocus.js';
import { InlineMessage, LoadingState } from '../../components/Feedback.jsx';
import { confirmDialog, notify } from '../../components/NotificationProvider.jsx';
import { isUncertainMutation } from '../../lib/mutation-outcome.js';
import { useDraftGuard } from '../../lib/draft-navigation.js';
import { messageFor } from '../../lib/messages.js';
export default function AddWorkspaceMember({ api, workspace, onClose }) {
  const { locale } = useAuthLocale();
  const t = (value, values) => workspaceText(value, locale, values);
  const [data, setData] = useState({ items: [] }), [q, setQ] = useState(''), [selected, setSelected] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [loadError, setLoadError] = useState(''), [busy, setBusy] = useState(false), [uncertain, setUncertain] = useState(false);
  const panel = useRef(null), pending = useRef(false), close = useRef(null), generation = useRef(0);
  useDraftGuard({ dirty: Boolean(selected), busy, message: t("Bỏ lựa chọn thành viên chưa thêm?"), busyMessage: t("Đang xử lý yêu cầu. Vui lòng chờ kết quả trước khi rời trang.") });
  close.current = async () => { if (!pending.current && (!selected || await confirmDialog(t("Bỏ lựa chọn thành viên chưa thêm?")))) onClose(); };
  useDialogFocus(panel, () => close.current());
  async function load(cursor, token = generation.current) { setLoading(true); setLoadError(''); try { const result = await api.request(`/organizations/${workspace.organizationId}/members?limit=12${q.trim() ? '&q=' + encodeURIComponent(q.trim()) : ''}${cursor ? '&cursor=' + encodeURIComponent(cursor) : ''}`); if (token === generation.current) setData(old => ({ ...result, items: cursor ? [...old.items, ...result.items] : result.items })); } catch (error) { if (token === generation.current) setLoadError(messageFor(error)); } finally { if (token === generation.current) setLoading(false); } }
  useEffect(() => { const token = ++generation.current; setData({ items: [] }); const timer = setTimeout(() => load(null, token), 250); return () => { clearTimeout(timer); generation.current++; }; }, [q, workspace.id]);
  async function submit(event) { event.preventDefault(); if (pending.current || uncertain || !selected) return; pending.current = true; setBusy(true); setError(''); try { const result = await api.request(`/organizations/${workspace.organizationId}/workspaces/${workspace.id}/members`, { method: 'POST', body: { expectedVersion: workspace.version, userId: selected.userId } }); notify(result.code === 'ALREADY_MEMBER' ? t("Người này đã tham gia Workspace.") : t("Đã thêm thành viên vào Workspace.")); onClose(); } catch (error) { setUncertain(isUncertainMutation(error)); setError(isUncertainMutation(error) ? t("Chưa xác nhận kết quả. Đóng và tải lại trước khi thêm tiếp.") : messageFor(error)); } finally { pending.current = false; setBusy(false); } }
  return createPortal(<div className="overlay"><section lang={locale} className="dialog" ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="workspace-add-title"><h2 id="workspace-add-title">{t("Thêm thành viên nội bộ")}</h2><p>{t("Chọn thành viên đang trong tổ chức để thêm ngay vào {name}, không cần chấp nhận lại.", { name: workspace.name })}</p><form onSubmit={submit}><fieldset disabled={busy || uncertain}><FormField label={t("Tìm thành viên tổ chức")}>{props => <input {...props} type="search" maxLength={200} value={q} onChange={event => setQ(event.target.value)} />}</FormField><FormField label={t("Thành viên được thêm")}>{props => <select {...props} value={selected?.userId ?? ''} onChange={event => setSelected(data.items.find(item => item.userId === event.target.value) ?? null)}><option value="">{t("Chọn thành viên")}</option>{selected && !data.items.some(item => item.userId === selected.userId) && <option value={selected.userId}>{selected.displayName}</option>}{data.items.map(item => <option key={item.userId} value={item.userId}>{item.displayName}</option>)}</select>}</FormField>{loading && <LoadingState>{t("Đang tải thành viên…")}</LoadingState>}{data.nextCursor && <button type="button" disabled={loading} onClick={() => load(data.nextCursor)}>{t("Tải thêm thành viên để chọn")}</button>}</fieldset>{error && <InlineMessage>{t(error)}</InlineMessage>}{loadError && <InlineMessage>{t(loadError)}<button type="button" disabled={busy} onClick={() => load()}>{t("Tải lại thành viên")}</button></InlineMessage>}<div className="buttons"><button type="button" disabled={busy} onClick={() => close.current()}>{t("Đóng")}</button><button className="primary" disabled={busy || uncertain || !selected}>{t("Thêm vào Workspace")}</button></div></form></section></div>, document.body);
}
