import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import FormField from '../../components/FormField.jsx';
import useDialogFocus from '../../components/useDialogFocus.js';
import { InlineMessage, LoadingState } from '../../components/Feedback.jsx';
import { confirmDialog, notify } from '../../components/NotificationProvider.jsx';
import { isUncertainMutation } from '../../lib/mutation-outcome.js';
import { useDraftGuard } from '../../lib/draft-navigation.js';
import { messageFor } from '../../lib/messages.js';
export default function AddWorkspaceMember({ api, workspace, onClose }) {
  const [data, setData] = useState({ items: [] }), [q, setQ] = useState(''), [selected, setSelected] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [loadError, setLoadError] = useState(''), [busy, setBusy] = useState(false), [uncertain, setUncertain] = useState(false);
  const panel = useRef(null), pending = useRef(false), close = useRef(null), generation = useRef(0);
  useDraftGuard({ dirty: Boolean(selected), busy, message: 'Bỏ lựa chọn thành viên chưa thêm?' });
  close.current = async () => { if (!pending.current && (!selected || await confirmDialog('Bỏ lựa chọn thành viên chưa thêm?'))) onClose(); };
  useDialogFocus(panel, () => close.current());
  async function load(cursor, token = generation.current) { setLoading(true); setLoadError(''); try { const result = await api.request(`/organizations/${workspace.organizationId}/members?limit=12${q.trim() ? '&q=' + encodeURIComponent(q.trim()) : ''}${cursor ? '&cursor=' + encodeURIComponent(cursor) : ''}`); if (token === generation.current) setData(old => ({ ...result, items: cursor ? [...old.items, ...result.items] : result.items })); } catch (error) { if (token === generation.current) setLoadError(messageFor(error)); } finally { if (token === generation.current) setLoading(false); } }
  useEffect(() => { const token = ++generation.current; setData({ items: [] }); const timer = setTimeout(() => load(null, token), 250); return () => { clearTimeout(timer); generation.current++; }; }, [q, workspace.id]);
  async function submit(event) { event.preventDefault(); if (pending.current || uncertain || !selected) return; pending.current = true; setBusy(true); setError(''); try { const result = await api.request(`/organizations/${workspace.organizationId}/workspaces/${workspace.id}/members`, { method: 'POST', body: { expectedVersion: workspace.version, userId: selected.userId } }); notify(result.code === 'ALREADY_MEMBER' ? 'Người này đã tham gia Workspace.' : 'Đã thêm thành viên vào Workspace.'); onClose(); } catch (error) { setUncertain(isUncertainMutation(error)); setError(isUncertainMutation(error) ? 'Chưa xác nhận kết quả. Đóng và tải lại trước khi thêm tiếp.' : messageFor(error)); } finally { pending.current = false; setBusy(false); } }
  return createPortal(<div className="overlay"><section className="dialog" ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="workspace-add-title"><h2 id="workspace-add-title">Thêm thành viên nội bộ</h2><p>Chọn thành viên đang trong tổ chức để thêm ngay vào {workspace.name}, không cần chấp nhận lại.</p><form onSubmit={submit}><fieldset disabled={busy || uncertain}><FormField label="Tìm thành viên tổ chức">{props => <input {...props} type="search" maxLength={200} value={q} onChange={event => setQ(event.target.value)} />}</FormField><FormField label="Thành viên được thêm">{props => <select {...props} value={selected?.userId ?? ''} onChange={event => setSelected(data.items.find(item => item.userId === event.target.value) ?? null)}><option value="">Chọn thành viên</option>{selected && !data.items.some(item => item.userId === selected.userId) && <option value={selected.userId}>{selected.displayName}</option>}{data.items.map(item => <option key={item.userId} value={item.userId}>{item.displayName}</option>)}</select>}</FormField>{loading && <LoadingState>Đang tải thành viên…</LoadingState>}{data.nextCursor && <button type="button" disabled={loading} onClick={() => load(data.nextCursor)}>Tải thêm thành viên để chọn</button>}</fieldset>{error && <InlineMessage>{error}</InlineMessage>}{loadError && <InlineMessage>{loadError}<button type="button" disabled={busy} onClick={() => load()}>Tải lại thành viên</button></InlineMessage>}<div className="buttons"><button type="button" disabled={busy} onClick={() => close.current()}>Đóng</button><button className="primary" disabled={busy || uncertain || !selected}>Thêm vào Workspace</button></div></form></section></div>, document.body);
}
