import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import FormField from '../../components/FormField.jsx';
import MemberPicker from '../../components/MemberPicker.jsx';
import useDialogFocus from '../../components/useDialogFocus.js';
import { InlineMessage, LoadingState, EmptyState } from '../../components/Feedback.jsx';
import { confirmDialog, notify } from '../../components/NotificationProvider.jsx';
import { useDraftGuard } from '../../lib/draft-navigation.js';
import { messageFor } from '../../lib/messages.js';
import { isUncertainMutation } from '../../lib/mutation-outcome.js';
const colors = { lavender: 'Tím', coral: 'Hồng', mint: 'Xanh mint', blue: 'Xanh dương', amber: 'Vàng', gray: 'Xám' };
const states = { active: 'Còn hiệu lực', expired: 'Hết hạn', accepted: 'Đã nhận', revoked: 'Đã thu hồi' };
export default function ProjectManagement({ api, project, onContext, onUnavailable }) {
  const [tab, setTab] = useState('labels'), [data, setData] = useState({ items: [] }), [busy, setBusy] = useState(true), [error, setError] = useState(''), [revision, setRevision] = useState(0), [action, setAction] = useState(null), generation = useRef(0);
  function changeTab(next) { if (next === tab) return; generation.current++; setData({ items: [] }); setError(''); setBusy(true); setTab(next); }
  async function load(cursor, token = generation.current) { setBusy(true); setError(''); try { const current = (await api.request(`/projects/${project.id}`)).project; if (token !== generation.current) return; onContext(current); if (tab !== 'labels' && !(tab === 'reopen-requests' ? current.permissions?.manageReopen : current.permissions?.manageAccess)) { setTab('labels'); setData({ items: [] }); return; } const result = await api.request(`/projects/${project.id}/${tab}?limit=12${cursor ? '&cursor=' + encodeURIComponent(cursor) : ''}`); if (token === generation.current) setData(old => ({ ...result, items: cursor ? [...old.items, ...result.items] : result.items })); } catch (error) { if (token === generation.current) { setError(messageFor(error)); setData({ items: [] }); if ([401,403,404].includes(error.status)) onUnavailable?.(error); } } finally { if (token === generation.current) setBusy(false); } }
  useEffect(() => { const token = ++generation.current; setData({ items: [] }); load(null, token); return () => { generation.current++; }; }, [project.id, tab, revision]);
  return <section className="project-management"><div className="section-heading"><h2>Quản lý Project</h2><button disabled={busy} onClick={() => setRevision(v => v + 1)}>Tải lại quản lý</button></div><p>Lead là quyền trong Project. Guest chỉ xem và bình luận, không tham gia Workspace hay nhận Task.</p><div className="team-tabs"><button aria-pressed={tab === 'labels'} onClick={() => changeTab('labels')}>Nhãn</button>{project.permissions?.manageAccess && <><button aria-pressed={tab === 'guests'} onClick={() => changeTab('guests')}>Guest</button><button aria-pressed={tab === 'guest-invitations'} onClick={() => changeTab('guest-invitations')}>Lời mời Guest</button></>}{project.permissions?.manageReopen && <button aria-pressed={tab === 'reopen-requests'} onClick={() => changeTab('reopen-requests')}>Yêu cầu mở lại</button>}{project.permissions?.manageLead && <button onClick={() => setAction({ kind: 'lead' })}>Thiết lập Lead</button>}</div>
    {tab === 'labels' && project.permissions?.manageLabels && <button className="primary" onClick={() => setAction({ kind: 'label' })}>Tạo nhãn</button>}{tab === 'guest-invitations' && project.permissions?.manageGuests && !project.readOnly && <button className="primary" onClick={() => setAction({ kind: 'invite' })}>Mời Guest</button>}
    {error && <InlineMessage>{error}</InlineMessage>}{busy && <LoadingState>Đang tải quản lý Project…</LoadingState>}<ul className="project-management-list">{data.items.map(item => <li key={item.id ?? item.userId}><div><strong>{tab === 'labels' ? item.name : tab === 'guests' ? item.displayName : tab === 'reopen-requests' ? `${item.task?.code ?? 'Task'} · ${item.task?.title}` : item.email ?? 'Liên kết Guest'}</strong><p>{tab === 'labels' ? item.archivedAt ? 'Nhãn đã lưu trữ' : colors[item.color] : tab === 'guests' ? 'Guest · Xem và bình luận' : tab === 'reopen-requests' ? `Yêu cầu của ${item.requester?.displayName ?? 'Thành viên'} · ${item.reason}` : `${states[item.state]} · Hết hạn ${new Date(item.expiresAt).toLocaleDateString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' })}`}</p></div><div className="buttons">{tab === 'reopen-requests' && <a href={`#task/${item.task.id}`}>{item.permissions?.review ? 'Xem và duyệt yêu cầu' : 'Xem yêu cầu'}</a>}{tab === 'labels' && project.permissions?.manageLabels && <button onClick={() => setAction({ kind: 'label', item })}>Sửa nhãn</button>}{tab === 'guests' && project.permissions?.manageAccess && <button onClick={() => setAction({ kind: 'remove', item })}>Thu hồi quyền Guest</button>}{tab === 'guest-invitations' && item.state === 'active' && project.permissions?.manageAccess && <button onClick={() => setAction({ kind: 'revoke', item })}>Thu hồi lời mời Guest</button>}</div></li>)}</ul>{!busy && !error && !data.items.length && <EmptyState>Chưa có dữ liệu trong danh sách này.</EmptyState>}{data.nextCursor && <button disabled={busy} onClick={() => load(data.nextCursor)}>Tải thêm danh sách</button>}{action && <ManagementDialog api={api} project={project} action={action} onClose={() => { setAction(null); setRevision(v => v + 1); }} />}
  </section>;
}
function ManagementDialog({ api, project, action, onClose }) {
  const [name, setName] = useState(action.item?.name ?? ''), [color, setColor] = useState(action.item?.color ?? 'lavender'), [archived, setArchived] = useState(Boolean(action.item?.archivedAt)), [leadId, setLead] = useState(project.leadId ?? ''), [type, setType] = useState('EMAIL'), [email, setEmail] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [uncertain, setUncertain] = useState(false), [result, setResult] = useState(null), [dirty, setDirty] = useState(false);
  const panel = useRef(null), pending = useRef(false), close = useRef(null), kind = action.kind;
  useDraftGuard({ dirty: dirty && !result, busy, message: 'Bỏ thay đổi Project chưa lưu?' });
  close.current = async () => { if (!pending.current && (!dirty || result || await confirmDialog(uncertain ? 'Đóng form và tải lại để kiểm tra thay đổi đã lưu chưa?' : 'Bỏ thay đổi Project chưa lưu?'))) onClose(); };
  useDialogFocus(panel, () => close.current());
  const title = { label: action.item ? 'Sửa nhãn' : 'Tạo nhãn', lead: 'Thiết lập Project Lead', invite: 'Mời Guest', remove: 'Thu hồi quyền Guest', revoke: 'Thu hồi lời mời Guest' }[kind];
  async function submit(event) { event.preventDefault(); if (pending.current || uncertain || result) return; pending.current = true; setBusy(true); setError(''); try { const base = `/projects/${project.id}`; let path, method = 'POST', body;
      if (kind === 'label') { path = base + '/labels' + (action.item ? '/' + action.item.id : ''); method = action.item ? 'PATCH' : 'POST'; body = { name: name.trim(), color, ...(action.item ? { archived, expectedVersion: action.item.version } : {}) }; }
      if (kind === 'lead') { path = base + '/lead'; method = 'PATCH'; body = { leadId: leadId || null, expectedVersion: project.version }; }
      if (kind === 'invite') { path = base + '/guest-invitations'; body = { type, ...(type === 'EMAIL' ? { email: email.trim() } : {}) }; }
      if (kind === 'remove' || kind === 'revoke') { path = base + (kind === 'remove' ? `/guests/${action.item.userId}/remove` : `/guest-invitations/${action.item.id}/revoke`); body = { expectedVersion: action.item.version }; }
      const response = await api.request(path, { method, body }); if (kind === 'invite') { setResult(response); setDirty(false); } else { notify('Đã cập nhật quản lý Project.'); onClose(); }
    } catch (error) { setUncertain(isUncertainMutation(error)); setError(isUncertainMutation(error) ? 'Chưa xác nhận kết quả. Đóng và tải lại trước khi gửi tiếp.' : messageFor(error)); } finally { pending.current = false; setBusy(false); } }
  return createPortal(<div className="overlay"><section ref={panel} tabIndex={-1} className="dialog project-management-dialog" role="dialog" aria-modal="true" aria-labelledby="project-manage-title"><h2 id="project-manage-title">{title}</h2><p>{project.name}</p>{result ? <><InlineMessage tone="info">{result.url ? 'Đã tạo liên kết Guest. Sao chép trước khi đóng; danh sách không lưu URL.' : 'Đã tạo lời mời Guest; email đang chờ gửi.'}</InlineMessage>{result.url && <FormField label="Liên kết Guest">{props => <textarea {...props} readOnly value={result.url} onFocus={event => event.target.select()} />}</FormField>}{result.url && <button onClick={async () => { try { await navigator.clipboard.writeText(result.url); notify('Đã sao chép liên kết Guest.'); } catch { notify('Chọn liên kết rồi sao chép thủ công.', 'info'); } }}>Sao chép liên kết Guest</button>}<button onClick={() => close.current()}>Đóng kết quả</button></> : <form onSubmit={submit}><fieldset disabled={busy || uncertain}>
    {kind === 'label' && <><FormField label="Tên nhãn" hint="Tối đa 60 ký tự; tên không được trùng trong Project.">{props => <input {...props} required maxLength={60} value={name} onChange={event => { setName(event.target.value); setDirty(true); }} />}</FormField><FormField label="Màu nhãn">{props => <select {...props} value={color} onChange={event => { setColor(event.target.value); setDirty(true); }}>{Object.entries(colors).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select>}</FormField>{action.item && <label className="check"><input type="checkbox" checked={archived} onChange={event => { setArchived(event.target.checked); setDirty(true); }} />Lưu trữ nhãn — giữ lịch sử Task, ngừng gán mới</label>}</>}
    {kind === 'lead' && <><p>Chọn thành viên đang tham gia Workspace. Lead quản lý Task trong Project, không quản trị Workspace hay cấp Guest.</p><MemberPicker label="Project Lead" api={api} workspaceId={project.workspaceId} value={leadId} selectedMember={project.leadId ? { userId: project.leadId, displayName: 'Lead hiện tại' } : undefined} disabled={busy || uncertain} onChange={value => { setLead(value); setDirty(true); }} /><p>Chọn không phân công để bỏ Lead.</p></>}
    {kind === 'invite' && <><p>Guest chỉ xem và bình luận ở Project này; không tạo/nhận Task. Lời mời có hạn 7 ngày.</p><FormField label="Cách mời Guest">{props => <select {...props} value={type} onChange={event => { setType(event.target.value); setDirty(true); }}><option value="EMAIL">Email</option><option value="LINK">Liên kết</option></select>}</FormField>{type === 'EMAIL' && <FormField label="Email Guest">{props => <input {...props} type="email" required maxLength={254} value={email} onChange={event => { setEmail(event.target.value); setDirty(true); }} />}</FormField>}</>}
    {kind === 'remove' && <p>Gỡ quyền Guest của {action.item.displayName}. Giữ Task, bình luận và lịch sử. Không phải Ban; người này có thể được cấp lại qua lời mời còn hiệu lực.</p>}{kind === 'revoke' && <p>Ngừng dùng lời mời này; không gỡ Guest đã tham gia và không rút email đã gửi.</p>}
    </fieldset>{error && <InlineMessage>{error}</InlineMessage>}<div className="buttons"><button type="button" disabled={busy} onClick={() => close.current()}>Đóng</button><button className="primary" disabled={busy || uncertain}>{busy ? 'Đang lưu…' : title}</button></div></form>}</section></div>, document.body);
}

