import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { InlineMessage, LoadingState, EmptyState } from '../../components/Feedback.jsx';
import FormField from '../../components/FormField.jsx';
import useDialogFocus from '../../components/useDialogFocus.js';
import { confirmDialog, notify } from '../../components/NotificationProvider.jsx';
import { useDraftGuard } from '../../lib/draft-navigation.js';
import { isUncertainMutation } from '../../lib/mutation-outcome.js';
import { messageFor } from '../../lib/messages.js';
const date = value => new Date(value).toLocaleString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' });
const choices = { none: 'Giữ bình luận', 1: '1 ngày gần nhất', 3: '3 ngày gần nhất', 7: '7 ngày gần nhất', 30: '30 ngày gần nhất', all: 'Toàn bộ bình luận' };
const states = { pending: 'Chờ xử lý', processing: 'Đang xử lý', completed: 'Đã hoàn tất', failed: 'Xử lý thất bại' };
export function BanDialog({ api, workspace, member, onClose }) {
  return <ModerationDialog api={api} workspace={workspace} target={member} kind="ban" onClose={onClose} />;
}
function ModerationDialog({ api, workspace, target, kind, onClose }) {
  const [cleanup, setCleanup] = useState('none'), [reason, setReason] = useState(''), [confirmation, setConfirmation] = useState(''), [preview, setPreview] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [uncertain, setUncertain] = useState(false);
  const pending = useRef(false), panel = useRef(null), close = useRef(null);
  useDraftGuard({ dirty: Boolean(reason || confirmation || cleanup !== 'none'), busy, message: 'Bỏ xác nhận kiểm soát truy cập chưa gửi?' });
  close.current = async () => { if (!pending.current && ((!reason && !confirmation && cleanup === 'none') || await confirmDialog('Đóng xác nhận kiểm soát truy cập?', { confirmLabel: 'Đóng' }))) onClose(); };
  useDialogFocus(panel, () => close.current());
  const base = `/moderation/workspace/${workspace.id}`;
  async function run(event, previewOnly = false) {
    event?.preventDefault(); if (pending.current || uncertain) return;
    pending.current = true; setBusy(true); setError('');
    try {
      if (previewOnly) { setPreview(await api.request(base + '/preview', { method: 'POST', body: { userId: target.userId, cleanup } })); return; }
      await api.request(kind === 'ban' ? base + '/bans' : base + `/bans/${target.userId}/unban`, { method: 'POST', body: kind === 'ban' ? { userId: target.userId, cleanup, reason: reason.trim(), expectedVersion: preview.expectedVersion, ...(cleanup !== 'none' ? { preview: preview.preview } : {}) } : { reason: reason.trim(), expectedVersion: target.version } });
      notify(kind === 'ban' ? 'Đã chặn truy cập. Bình luận cần dọn được xếp hàng xử lý.' : 'Đã bỏ chặn. Người này chưa được cấp lại quyền tham gia.'); onClose();
    } catch (error) { setUncertain(isUncertainMutation(error)); setError(isUncertainMutation(error) ? 'Chưa xác nhận kết quả. Đóng và tải lại trước khi thao tác tiếp.' : messageFor(error)); if (kind === 'ban') setPreview(null); }
    finally { pending.current = false; setBusy(false); }
  }
  const validReason = reason.trim() && !/[\u0000-\u001f\u007f\u2028\u2029]/u.test(reason);
  return createPortal(<div className="overlay"><section ref={panel} tabIndex={-1} className="dialog moderation-dialog" role="dialog" aria-modal="true" aria-labelledby="moderation-title"><h2 id="moderation-title">{kind === 'ban' ? 'Chặn truy cập Workspace' : 'Bỏ chặn truy cập'}</h2><p><strong>{target.displayName ?? target.userId}</strong> · {workspace.name}</p><form onSubmit={event => run(event)}><fieldset disabled={busy || uncertain}>
    <p>{kind === 'ban' ? 'Thu hồi quyền trong Workspace này và chặn dùng lại lời mời còn hiệu lực. Task chưa Done bỏ assignee; Task Done và lịch sử được giữ. Không ảnh hưởng Workspace khác.' : 'Bỏ chặn không tự khôi phục membership, Task assignee hoặc quyền Project. Cần thêm/mời lại theo quyền hiện tại. Bỏ chặn không hủy công việc dọn bình luận đã xếp hàng.'}</p>
    {kind === 'ban' && <FormField label="Bình luận cần dọn" hint="Chỉ bình luận của người này trong Workspace, kể cả Project lưu trữ. Task và tài liệu được giữ.">{props => <select {...props} value={cleanup} onChange={event => { setCleanup(event.target.value); setPreview(null); setConfirmation(''); }}>{Object.entries(choices).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select>}</FormField>}
    <FormField label="Lý do" hint="Một dòng, tối đa 2.000 ký tự; ghi vào nhật ký.">{props => <input {...props} required maxLength={2000} value={reason} onChange={event => setReason(event.target.value)} />}</FormField>
    {kind === 'ban' && <><button type="button" onClick={() => run(null, true)}>Xem trước tác động</button>{preview && <InlineMessage tone="info">{preview.matchedCount} bình luận thuộc phạm vi đã chọn. Mốc chốt: {date(preview.cutoff)}. Số xử lý thực tế được cập nhật ở nhật ký.</InlineMessage>}{cleanup !== 'none' && <><p>Bình luận đã dọn sẽ bị xóa vĩnh viễn, không vào thùng rác.</p><FormField label="Xác nhận dọn bình luận" hint="Nhập XÓA BÌNH LUẬN để xác nhận.">{props => <input {...props} value={confirmation} onChange={event => setConfirmation(event.target.value)} />}</FormField></>}</>}
    </fieldset>{error && <InlineMessage>{error}</InlineMessage>}<div className="buttons"><button type="button" disabled={busy} onClick={() => close.current()}>Đóng</button><button className="primary" disabled={busy || uncertain || !validReason || (kind === 'ban' && (!preview || (cleanup !== 'none' && confirmation !== 'XÓA BÌNH LUẬN')))}>{busy ? 'Đang xử lý…' : kind === 'ban' ? 'Chặn truy cập' : 'Bỏ chặn'}</button></div></form></section></div>, document.body);
}
export default function WorkspaceModeration({ api, workspace }) {
  const [tab, setTab] = useState('bans'), [data, setData] = useState({ items: [] }), [busy, setBusy] = useState(true), [error, setError] = useState(''), [revision, setRevision] = useState(0), [target, setTarget] = useState(null), [retrying, setRetrying] = useState(false), [uncertain, setUncertain] = useState(false), generation = useRef(0), pending = useRef(false);
  const base = `/moderation/workspace/${workspace.id}`;
  async function load(cursor, token = generation.current) { setBusy(true); setError(''); try { const result = await api.request(`${base}/${tab}?limit=12${cursor ? '&cursor=' + encodeURIComponent(cursor) : ''}`); if (token === generation.current) { setData(old => ({ ...result, items: cursor ? [...old.items, ...result.items] : result.items })); setUncertain(false); } } catch (error) { if (token === generation.current) { setError(messageFor(error)); setData({ items: [] }); } } finally { if (token === generation.current) setBusy(false); } }
  useEffect(() => { const token = ++generation.current; setData({ items: [] }); load(null, token); return () => { generation.current++; }; }, [workspace.id, workspace.version, tab, revision]);
  async function retry(item) { if (pending.current || uncertain || !await confirmDialog('Xếp hàng xử lý lại phần bình luận còn lại? Giữ nguyên người, phạm vi và mốc thời gian của lần Ban.', { confirmLabel: 'Xếp hàng lại' })) return; pending.current = true; setRetrying(true); try { await api.request(`${base}/actions/${item.id}/retry`, { method: 'POST', body: { expectedVersion: item.version } }); notify('Đã xếp hàng xử lý lại.'); setRevision(v => v + 1); } catch (error) { setUncertain(isUncertainMutation(error)); setError(isUncertainMutation(error) ? 'Chưa xác nhận kết quả. Tải lại trước khi tiếp tục.' : messageFor(error)); } finally { pending.current = false; setRetrying(false); } }
  return <section className="workspace-moderation"><h2>An toàn truy cập</h2><p>Chặn theo Workspace. Bỏ chặn không tự cấp lại quyền; việc dọn bình luận được xử lý nền và có nhật ký.</p><div className="team-tabs"><button aria-pressed={tab === 'bans'} onClick={() => setTab('bans')} disabled={retrying}>Danh sách chặn</button><button aria-pressed={tab === 'actions'} onClick={() => setTab('actions')} disabled={retrying}>Nhật ký xử lý</button><button disabled={busy || retrying} onClick={() => setRevision(v => v + 1)}>Tải lại</button></div>{error && <InlineMessage>{error}</InlineMessage>}{busy && <LoadingState>Đang tải trạng thái kiểm soát truy cập…</LoadingState>}<ul className="audit-list">{data.items.map(item => <li key={item.id}><strong>{item.displayName ?? item.targetDisplayName ?? item.userId ?? item.targetUserId}</strong>{tab === 'bans' ? <><p>{item.state === 'active' ? 'Đang chặn' : 'Đã bỏ chặn'} · {item.reason}</p><time>{date(item.imposedAt)}</time>{item.state === 'active' && <button disabled={busy || retrying || uncertain} onClick={() => setTarget(item)}>Bỏ chặn</button>}</> : <><p>{item.action === 'ban' ? 'Chặn truy cập' : item.action === 'unban' ? 'Bỏ chặn' : 'Xóa bình luận'} · {states[item.state]}</p><p>{item.reason}</p><p>{item.deletedCount}/{item.matchedCount} bình luận đã xử lý · {choices[item.cleanup]} · Mốc {date(item.cutoff)}</p>{item.lastErrorCode && <InlineMessage>Đợt dọn bình luận gặp lỗi. Có thể xếp hàng lại để xử lý phần còn lại.</InlineMessage>}{item.state === 'failed' && item.action === 'ban' && item.cleanup !== 'none' && <button disabled={busy || retrying || uncertain} onClick={() => retry(item)}>Xếp hàng xử lý lại</button>}</>}</li>)}</ul>{!busy && !error && !data.items.length && <EmptyState>Chưa có dữ liệu trong danh sách này.</EmptyState>}{data.nextCursor && <button disabled={busy || retrying} onClick={() => load(data.nextCursor)}>Tải thêm</button>}{target && <ModerationDialog api={api} workspace={workspace} target={target} kind="unban" onClose={() => { setTarget(null); setRevision(v => v + 1); }} />}</section>;
}
